### ISSUE TITLE
Match DevSecOps naming convention

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1077]
The DevSecOps/OET team has naming conventions for their Azure resources, so to be good tenants, we should abide by them. [Some notes about them.](https://docs.google.com/document/d/1vActZALSbRwO0HxDvm-YQK37p22SPbL4XuMdcRx-BI8/edit#bookmark=id.oh68cvyl32ig)

## Acceptance Criteria

- [ ] All resources match the DevSecOps naming convention

## Tasks

- [x] Get written rules from DevSecOps
- [ ] Update existing resources
- [ ] Add / link to documentation

**Comment by thekaveman** [comment]
@angela-tran I think we've done this, correct?

**Comment by angela-tran** [comment]
@thekaveman Yeah, I think #1074 accomplished this. 

I do see a [comment](https://github.com/cal-itp/benefits/pull/1074#discussion_r1055041360) that implies this ticket here also covers standardizing further / removing inconsistencies within CDT's naming (especially for resources we don't have permission to modify), but that seems like scope creep to me. We at least have those inconsistencies codified in Terraform, so I think until they pose a problem, we can leave them be.
