### ISSUE TITLE
Get College Milestone Copy translated into Spanish

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1121]
The College Milestone copy needs to be translated into Spanish.

## Acceptance Criteria

- [ ] Compile, submit current English/Spanish Style Guide
- [ ] Submit TODOs in Spanish django.po file
- [ ] Get it translated

## Additional context

- Babble-on to translate
- Machiko to manage translation update

**Comment by machikoyasuda** [comment]
This part can be done in a separate ticket:

https://support.crowdin.com/github-integration/

**Comment by machikoyasuda** [comment]
```
Hi Vyki and Machiko,

The setup with GitHub is pretty straightforward. Here is a link to the documentation:

https://support.crowdin.com/github-integration/

Once you’re ready, I can create a project in Crowdin and invite your developers so they can do the setup. From there, the push and pull of files becomes trivial and they'll only need to commit translations once they’re sent back to GitHub.

Let me know if you have any questions.

Best,

Salim
Babble-on Translations


> On Nov 3, 2022, at 10:55 AM, Salim Martell <[salim@ibabbleon.com](mailto:salim@ibabbleon.com)> wrote:
>
> Hi Vyki,
>
> That sounds great! We might need to do this first round manually though. We typically don’t edit PO files so it depends on what you’re referring to. Reviewing and merging pull requests is not something we do. We work with GitHub to set up an integration and automate the push/pull of files, but there is usually some dev work to do on your end, which is generally managing the pull requests. I’ll get some clarification and get back to you.
>
> Salim
> Babble-on Translations
```

**Comment by machikoyasuda** [comment]
I will start this integration post-CC launch.

**Comment by angela-tran** [comment]
The User Error pages were done in #1218

**Comment by angela-tran** [comment]
This now seems duplicative of #1189

**Comment by machikoyasuda** [comment]
I'm good with closing this in favor of #1189
