### ISSUE TITLE
Improve secrets management

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1163]
In https://github.com/cal-itp/benefits/issues/1143, we determined that we want to go from the data migration file being treated as one big secret to the file loading secrets it needs at runtime (e.g. as environment variables).

## Acceptance Criteria

- [ ] We are managing secrets as individual values rather than all in one file
- [ ] We minimize the number of places that secrets are stored
- [ ] Secrets are stored in a secure location

## Tasks
- [x] Modify the [existing data migration](https://github.com/cal-itp/benefits/blob/dev/benefits/core/migrations/0002_sample_data.py) to read from environment variables - #1198
- [x] #1242
   - (support for environment-specific Vaults was added in [#830](https://github.com/cal-itp/benefits/issues/830))
- [ ] #1241
- [ ] #1243
- [ ] #1244
   - Delete data migration files from benefits-secrets
   - Delete/rename data migration file from each bucket
   - Delete storage mount from Terraform Azure definition
 - [ ] #1245

## Additional context

See #1143 and #1116 for more context on past situations that motivated this refactor.

**Comment by angela-tran** [comment]
Talked with @thekaveman about working on this while we wait for #1090. The first part will be to update our data migration file to read environment variables.

**Comment by thekaveman** [comment]
Moved description into Milestone, closing.
