### ISSUE TITLE
Production checklist

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#119]
* [ ] Create `.github/workflows/ecs-deploy-prod.yml` based on existing files for [`dev`](https://github.com/cal-itp/benefits/blob/dev/.github/workflows/ecs-deploy-dev.yml) and [`test`](https://github.com/cal-itp/benefits/blob/dev/.github/workflows/ecs-deploy-test.yml)
* [ ] Configure secrets in `prod` environment
  * `AWS_ACCESS_KEY_ID`
  * `AWS_ACCOUNT`
  * `AWS_BUCKET`
  * `AWS_SECRET_ACCESS_KEY`
* [ ] Add `.env` and `config.json` files to bucket
  * Verify `ALLOWED_HOSTS`
  * Verify amplitude API creds
  * Verify eligibility API creds
  * Verify payment processor API creds
* [ ] Configure domain in Route53
* [ ] Verify ELB subnets are *Outside*
* [ ] Add `aws-cli` image to ECR

**Comment by thekaveman** [comment]
Closed by #145 and #146
