### ISSUE TITLE
Collect errors in Sentry

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1258]
https://github.com/cal-itp/benefits/issues/861 is getting long, so splitting this issue out.

## Acceptance Criteria

- [x] Application errors are being collected by Sentry

## Tasks

- [x] Get access to Sentry
- [x] Create a Project for Benefits
- [x] Set up the SDK
- [x] Set the environment variables - https://github.com/cal-itp/benefits-secrets/pull/34
  - [x] Dev
  - [x] Test
  - [x] Prod
- [x] Ensure we can distinguish which [environment](https://docs.sentry.io/product/sentry-basics/environments/) errors are coming from
- [x] Send notifications to Slack
- [x] Set up GitHub integration
- [ ] Remove Azure Monitor - https://github.com/cal-itp/benefits/pull/1261
  - [ ] Remove environment variable
  - [x] Remove OpenCensus
  - [x] Clean up docs

**Comment by afeld** [comment]
[Added a section in the Services Team Handbook.](https://docs.google.com/document/d/1Vb4JFb4UwRqqjeQXrkwqQDOvR-vJJceMi4S1_JbnehM/edit#heading=h.83fs1s6cm2qe)
