### ISSUE TITLE
Make a Release: 2023.02.1

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1283]
### Release manager

@angela-tran

### Release version

2023.02.1

### What type of release is this?

Hotfix

### Release checklist

- [x] Make the hotfix in a branch from `prod`
- [x] Bump the application version
- [x] Open a PR from the hotfix branch into prod, merge - #1285
- [x] QA the fix in prod
- [x] Tag the release on the prod branch, push the tag to GitHub
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed
- [x] Apply hotfix to `dev`
   - [x] Create a branch off `dev`
   - [x] Open a PR from `prod` into that branch, merge - #1286 
   - [x] (optional) Adapt hotfix to current state of `dev` in that same branch - #1287 
   - [x] Merge the PR into `dev`

**Comment by angela-tran** [comment]
Thanks for all your help @thekaveman !
