### ISSUE TITLE
Make a Release: 2023.03.2

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1330]
### Release manager

@angela-tran

### Release version

2023.03.2

### What type of release is this?

Regular

### Release checklist

- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into the staging target, merge - #1331 
- [x] ~(If applicable): update staging data migrations~ dev secrets are up-to-date
- [x] (If applicable): open another PR from dev to test - #1332
- [x] ~(If applicable): update data migrations~ - I updated the auth scope for the `test` Key Vault and checked over most of the secrets that will be used by the data migration - looks good ✅ - _edit_: we needed to make fix #1337 
- [x] QA the app in test
- [x] ~(If applicable): prepare production data migrations~ verified secrets in prod key vault
- [x] Open a PR to for the test branch into prod, merge - #1341
- [x] QA the app in prod - noticed there was a read timeout on a call to eligibility-server, worked when we tried it again. Will fix in a follow-up PR
- [x] Tag the release on the prod branch, push the tag to GitHub
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by angela-tran** [comment]
I am planning on working on this on Monday (March 27)

**Comment by angela-tran** [comment]
Reminder @angela-tran : update the auth scope secret for `test` and `prod` before deploying to them! See https://github.com/cal-itp/benefits-secrets/pull/20 for more context

**Comment by angela-tran** [comment]
Finished this yesterday with [release 2023.03.2](https://github.com/cal-itp/benefits/releases/tag/2023.03.2), and now closing
