### ISSUE TITLE
Make a Release: 2023.04.1

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1346]
### Release manager

@angela-tran

### Release version

2023.04.1

### What type of release is this?

Regular

### Release checklist

- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into the staging target, merge - #1347
- [x] ~(If applicable): update staging data migrations~
- [x] (If applicable): open another PR from dev to test - #1348
- [x] ~(If applicable): update data migrations~
- [x] QA the app in test - @angela-tran 
- [x] ~(If applicable): prepare production data migrations~
- [x] Open a PR to for the test branch into prod, merge - #1349 
- [x] QA the app in prod - @angela-tran 
- [x] Tag the release on the prod branch, push the tag to GitHub
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by angela-tran** [comment]
2023.04.1 has been released! 🎉
