### ISSUE TITLE
Make a Release: 2023.04.2

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1368]
### Release manager

@thekaveman

### Release version

2023.04.2

### What type of release is this?

Regular

### Release checklist

- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into dev, merge #1370
- [x] Update secrets in test
- [x] Open another PR from dev to test #1371 #1373
- [x] Merge PR to test
- [x] QA the app in test
- [x] Prepare production secrets
- [x] Open a PR to for the test branch into prod, merge #1375
- [x] QA the app in prod
- [x] Tag the release on the prod branch, push the tag to GitHub 
- [x] Create a release in GitHub for the tag, generating release notes https://github.com/cal-itp/benefits/releases/tag/2023.04.2
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by thekaveman** [comment]
Completed on Friday 4/21/23
