### ISSUE TITLE
SBMTD operational readiness

### ISSUE THREAD

**Issue by MarikoLochridge** [cal-itp/benefits#1409]
## Acceptance Criteria

- [x] Onboarding kickoff meeting: #1252 to complete onboarding worksheet (Let's add a link to this worksheet. Could this worksheet be published on calitp docs?)

- [x] Onboarding interview: Cal-ITP team and transit provider staff meet to confirm understanding of local transit services, implementation plan is feasible, and any approvals needed have been obtained. Confirm their fare structure in order to determine how many products need to be implemented into Little Pay. Here is the document to refer to [[WIP] Cal-ITP Benefits Transit Provider Onboarding Guide](https://docs.google.com/document/d/1D6li-i8ScY3D1-P-0qyh_9-UHwD6JGRyvf77V7LZncM/edit))  (- this needs to become a non-Google doc intake form for agencies @indexing )

- [x]  Configure Littlepay: Transit Provider creates discount products in Littlepay; Cal-ITP team creates concession groups and associates with discount products in Littlepay (Does this eventually get its own ticket?)

- [x]  Configure Benefits app: Cal-ITP team configures Benefits app with new transit provider information. (Does this eventually get its own ticket?)

- [x] Product to complete user stories #1395 

- [x]  Test: Cal-ITP team and Transit Provider test new configurations work and discounted-fares are accurately processed. (Acceptance Testing ticket and/or Product Validation Ticket TBC)

- [x]  Training: Cal-ITP team provides customer service training for Transit Provider staff. ([Cal-ITP Benefits Customer Service Docs](https://docs.google.com/document/d/1DBDY5_urdjn1AShWiXnB-2W4gVvN-t3dtoJb7WlY968/edit#heading=h.gzwq5fc2huor))

- [ ]  Launch: Launch app and distribute communications (#1267)

## Resources

| Doc Name | Doc Link | Status | Next Steps  | 
|:--|:--|:--| :--|
| Cal-ITP Benefits Transit Provider Onboarding | [Link](https://docs.google.com/document/d/1D6li-i8ScY3D1-P-0qyh_9-UHwD6JGRyvf77V7LZncM/edit#heading=h.h16xy885mvgv) | WIP | Move this documentation to be reflected within this ticket and/or Cal-ITP Docs Site, Possibly part of an email automation welcoming new clients. |
|  Cal-ITP Benefits Transit Provider Onboarding: Agency Card | [Link](https://docs.google.com/document/d/1pHfDjiIz1N-7P0nm1SAKeFdhf21eBj8ECdB70rzyPHo/edit) | Status | This feels a little duplicative of 'Cal-ITP Benefits Transit Provider Onboarding' - could the different user types become a table within this doc? |
| [SBMTD] Cal-ITP Benefits Transit Provider Onboarding: Agency Card | [Link](https://docs.google.com/document/d/1dLU5bLBDuEgR2MxtjPQxZls9OqCmDGJnG646VMO-PnY/edit) | Status | Feels like a duplicate? |
| Cal-ITP Benefits Transit Provider Onboarding: Seniors | [Link](https://docs.google.com/document/d/1L0M0LhYvSOPlU1OuVM2ZAzwQ7bq6_MFvw-GT1RC5ibs/edit) | Status | This feels a little duplicative of 'Cal-ITP Benefits Transit Provider Onboarding' - could the different user types become a table within this doc? |
| Creating a Discount Product | [Link](https://docs.google.com/document/d/1DZq-pZ2d8_X0NFzNGgkCUTcW0o8VFzGlWlkI4EMxqr8/edit#heading=h.fbckifx17szz) | Status | This feels like technical documentation that needs to be published on the docs site |
| Cal-ITP Benefits Terms of Service_template_seniors | [Link](https://docs.google.com/document/d/1IRrhLksMBODv8rY535UExHpxC4qSRgxbx-bB8TMzUtI/edit) | Status | Is this necessary? |
| Cal-ITP Benefits: Production validation testing plan | [Link](https://docs.google.com/document/d/17_gD9bFn_WIEY9mtK6gpx9hOWZddEsvQy9OqdEP2VuA/edit#heading=h.mbch5vj6z16d) | Status | Could this be made into a template within GitHub for better communication with dev? |
| Questions for Agency Onboarding | [Link](https://docs.google.com/document/d/1LGZ4_5sPSH6aB0FviOXh4EzeguYdasSXtTyRMt6KJQk/edit) | Status | This can be archived |
| Cal-ITP Payments Onboarding | [Link](https://docs.google.com/presentation/d/1nDqDsneoi512XfTQGx-Z9vmRJiCrEcwlmwGuFxa6zkM/edit#slide=id.g14442af2794_0_6) | Status | Determine if this is relevant to this ticket or not. |

## What is the definition of done?

Product validation has been successfully completed, agency has received all communications materials to promote product. Product solution is completed and then transferred to maintenance. All maintenance issues will be handled via HubSpot support intake (general email and/or assigned agent). The maintenance issue is then communicated and handed off to product to determine what tickets need to be created under which classification.

**Comment by MarikoLochridge** [comment]
@o-ram @indexing I have updated this ticket to reflect our last meeting, please take a look and let me know if anything is not accurately reflected. I will continue to work on connecting all resource docs regarding onboarding to this ticket.

**Comment by MarikoLochridge** [comment]
@MarikoLochridge to do an audit of all agency onboarding docs and organize into a table

**Comment by MarikoLochridge** [comment]
@o-ram @indexing I completed the inventory of onboarding docs that I found in the Google Drive and included them in the table above - listed under resources. Please drop links to any docs that I missed and I'll add them in.

**Comment by machikoyasuda** [comment]
- Cal-ITP Benefits Transit Provider Onboarding: SBMTD x Seniors doc from Feb/March 2023
https://docs.google.com/document/d/1gslfEV_TjWdRmMNdOe90pDUWbm8xyDZC/edit

- SBMTD full color logo PNG
https://drive.google.com/file/d/1YG7SU7YObpOEWqYSBcOHPO1I79byPhjd/view

**Comment by o-ram** [comment]
@indexing hope this isn't the wrong place for these but since it's a checklist item here and I didn't see another ticket that seemed fitting, putting them here.

Discount products for SBMTD are created! There are 2 - one for the senior group and one for the agency card group. I have the product codes for both, but no IDs. If the IDs are needed, I will get those from Hillary as soon as I am able.

- Senior group Product Code: **Senior 65+**
- Agency card group Product Code: **Person with Disabilities**
![image001 (11)](https://github.com/cal-itp/benefits/assets/92001064/56fd021d-9b06-463b-a689-f5455e07e9e6)

![image002 (3)](https://github.com/cal-itp/benefits/assets/92001064/fe00cbe4-877b-4826-8c2e-93bd5673b9c9)



Discount capping products that go along with both of these groups are almost done being created. Once we have those screenshots, those details can also be added to this issue!

**Comment by indexing** [comment]
@thekaveman See above for SBMTD Littlepay discount product group details.

**Comment by o-ram** [comment]
@indexing @thekaveman so sorry, I thought I had actually commented this the other day, but apparently just had my comment in preview mode 🙃 

I can confirm that the discount products in my above comment are correct! Below are the discount capping products that have been created.

Discount Capping Products:
SBMTD decided to create a discount fare cap for each group. Luckily, they only have a monthly discount fare cap. Below are the screenshots (the screenshots were again w/o URL but can go back and ask for IDs)
Cap for mobility pass group:
![image002 (5)](https://github.com/cal-itp/benefits/assets/92001064/3b8e9012-d414-4f18-9385-3a6f96d9ea6e)

Cap for senior group:
![image001 (13)](https://github.com/cal-itp/benefits/assets/92001064/10cd38a3-06fb-4118-9910-dce54d92afad)

**Comment by machikoyasuda** [comment]
Update: Today the Engineering team changed the `sbmtd_active` value from False to True on production. We noticed an issue with LittlePay on Test and Dev, so we are investigating it.

**Comment by indexing** [comment]
@o-ram Now that the SBMTD Older Adults pathway is live, I believe we can close this issue. SBMTD will handle production validation internally on their timeline. Please confirm you've provided initial training and documentation. If you agree, please proceed with closing the issue. Cheers!

**Comment by o-ram** [comment]
Confirming that initial training and documentation have been provided. SBMTD staff has the testing guide and customer service staff materials and we continue to stand by to support and provide further training as needed. Closing this issue!
