### ISSUE TITLE
[Tracking] Veteran eligibility verification with VA.gov

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1413]
## User story
_As a US Veteran living in California, I want to verify my eligibility for benefits with my transit agency using VA.gov, so I receive a discounted fare when I use my credit or debit card to pay for rides on public transit._

## Specifications

- We implemented use of the [Veteran Confirmation API](https://developer.va.gov/explore/api/veteran-confirmation/docs?version=current) in this story: #1691.
- For this story, we will add support for the [Veteran Service History and Eligibility API](https://developer.va.gov/explore/api/veteran-service-history-and-eligibility/docs?version=current) to allow veterans to use any method of authentication they use for VA.gov to verify identity through the gateway.

## Related Issues
- #1327
- #1326 
- #1429 

## Acceptance criteria

- [x] A Veteran can complete eligibility verification using the Benefits app in all supported web browsers running on a desktop device.
- [x] A Veteran can complete eligibility verification using the Benefits app in all supported  web browsers running on a mobile device. 

## Definition of "Done"

- [x] Veteran eligibility module passes all unit tests and integration tests.
- [x] Veteran eligibility module is deployed to production.
- [x] Veteran eligibility module can be enabled for one or more transit agencies.
- [x] Veteran eligibility enrollments are tracked in the Amplitude enrollment metric.
- [x] Veteran eligibility transactions are tracked in the Metabase payments processed metric.
- [x] Documentation at https://docs.calitp.org/benefits/use-cases/ is updated to cover the Veteran use case.

## Relevant resources

- [Veterans: Phase 2 Eligibility Verification: Design Brief (+ MST CC)
](https://docs.google.com/document/d/1A3fO6_HEorOMRyd5GzUoGrEbjqZpiAIA6CjmV4zvbIE/edit?usp=sharing)

**Comment by indexing** [comment]
Now that we support Veterans enrollment using Login.gov, @jarrettkrumrei and @johnatstate have begun the process to get authority on the Veteran Service History and Eligibility API.

**Comment by machikoyasuda** [comment]
Can this ticket be closed @indexing ?

**Comment by indexing** [comment]
@machikoyasuda This ticket covers support for the additional API from va.gov ([Veteran Service History and Eligibility API](https://developer.va.gov/explore/api/veteran-service-history-and-eligibility/docs?version=current)). 

In the short term, support for this API is an enhancement to the existing enrollment pathways that will allow Veteran users to use all authentication options offered by va.gov and not only Login.gov. Thus, it'll be open into 2024 as we await authority to operate.

**Comment by indexing** [comment]
Since gaining access to the VSHE API has proved to be it own endeavor and this API will likely cover new eligibility, such as disability, I am closing this issue. We will create a set of new issues that scope this as a clear, distinct effort. The first of which is #2294.
