### ISSUE TITLE
List of all the copy, user interface and style changes that are in the Veterans flow

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1440]
This is a list of all the changes in the Veterans flow, that are not already represented in tickets.

## Full list
- [ ] 1. **footer:** **CODE** external link icon (test the external link icon WITH link focus ring as well #1471 
- [ ] 2. **home page/agency page:** **ONLY COPY** / spanish ready #1386 
- [ ] 3. **eligibility index:** **ONLY COPY** for title (`Choose the transit benefit you would like to enroll in`) / spanish not read #1472
- [ ] 4. **eligibility index:** **ONLY COPY** for blurb - shortened and removes link (`Cal-ITP doesn’t save any of your information. All CST transit benefits reduce fare by 50% for bus service on fixed routes. #1472
- [ ] 5. **eligibility index:** login.gov - **CODE AND COPY** shorten radio button title to `Older Adult`, shorten radio button blurb, add new Login.gov logo image, and add question mark modal link #1473
- [ ] 6. **eligibility index:** login.gov - **MODAL** create modal #1473
- [ ] #1478
- [ ] 8. **eligibility index:** cc - **COPY ONLY** shorten radio button blur #1472
- [ ] 9. **eligibility index:** **DELETION** remove `Not sure which option is right for you? Please visit [HelpPage](https://dev-benefits.calitp.org/help).`  #1472
- [ ] 10. **eligibility start:** cc - **COPY ONLY** add the word `transit` to the headline #1474
- [ ] 11. **eligibility start:** login.gov - **COPY ONLY** add the word `transit` to the headline #1474
- [ ] 12. **eligibility start:** login.gov - **CODE AND COPY** media item - modal link and add new copy about phone number #1476
- [ ] 13. **eligibility start:** login.gov - **MODAL** create modal with external link #1476
- [x] 14. **eligibility start:** veterans - **CODE AND COPY** media item - bulleted list copy #1441 
- [ ] 15. **eligibility start:** ALL flows - payment media item - **COPY ONLY** copy for title #1474
- [ ] 16. **eligibility start:** ALL flows - payment media item - **COPY ONLY** copy for description, with modal link  #1474
- [ ] 17. **eligibility start:** ALL flows - payment media item - **MODAL** create modal with external link #1475
- [ ] 18. **eligibility start:** ALL flows - **DELETION** remove `Questions about the items above? Please visit our Help Page.`  #1474
- [ ] 19. **eligibility confirm:** cc - **DELETION** remove 1 paragraph #1482
- [ ] 20. **enrollment index:** ALL flows - **COPY** change title to `Your eligibility is confirmed! You’re almost there.` #1480
- [ ] 21. **enrollment index:** ALL flows - **DELETION** remove top media item #1479
- [ ] 22. **enrollment index:** ALL flows - **COPY ONLY** payment media item - change copy on LittlePay media item #1480
- [ ] 23. **enrollment index:** ALL flows - **MODAL** create modal with external link #1481
- [ ] 24. **enrollment success:** ALL flows - **CODE** change headline, add image and login.gov logo #1432
- [ ] #1484
- [ ] 26. **ALL app:** **STYLE** color change from 1 blue to another #1423 
- [ ] 27. **ALL app:** **STYLE NEEDS TESTING** color change for hover color, text link color, hover link color #1423 
- [ ] 28. **ALL app:** **STYLE NEEDS TESTING** focus ring for text links #1387 
- [ ] 29. **ALL app:** **CODE & COPY** skip nav #1388 

### How to prioritize?
- Tickets that can be de-prioritized entirely
- Tickets that are optional
- Tickets that are not optional / Tickets that must go together (usually deletion goes with a modal ticket)

### Prioritizing

Machiko's opinionated attempt

#### De-prioritized
- [ ] 1. **footer:** **CODE** external link icon (test the external link icon WITH link focus ring as well
- [ ] 24. **help page:** **CODE** add the new external link icon
- [ ] 25. **ALL app:** **STYLE** color change from 1 blue to another #1423 
- [ ] 27. **ALL app:** **STYLE NEEDS TESTING** focus ring for text links #1387 
- [ ] 28. **ALL app:** **CODE & COPY** skip nav #1388 
- [ ] 26. **ALL app:** **STYLE NEEDS TESTING** color change for hover color, text link color, hover link color #1423 

#### Nice to have
- [ ] 2. **home page/agency page:** **ONLY COPY** / spanish ready #1386 
- [ ] 23. **enrollment success:** ALL flows - **CODE** change headline, add image and login.gov logo https://github.com/cal-itp/benefits/issues/1432
- [ ] 6. **eligibility index:** login.gov - **MODAL** create modal
- [ ] 13. **eligibility start:** login.gov - **MODAL** create modal with external link
- [ ] 22. **enrollment index:** ALL flows - **MODAL** create modal with external link
- [ ] 16. **eligibility start:** ALL flows - payment media item - **MODAL** create modal with external link
- [ ] 7. **eligibility index:** veteran - **CODE** add external link icon to VA.gov link

#### Must have
- [ ] 3. **eligibility index:** **ONLY COPY** for title (`Choose the transit benefit you would like to enroll in`) / spanish not read
- [ ] 4. **eligibility index:** **ONLY COPY** for blurb - shortened and removes link (`Cal-ITP doesn’t save any of your information. All CST transit benefits reduce fare by 50% for bus service on fixed routes.
- [ ] 5. **eligibility index:** login.gov - **CODE AND COPY** shorten radio button title to `Older Adult`, shorten radio button blurb, add new Login.gov logo image, and add question mark modal link
- [ ] 8. **eligibility index:** cc - **COPY ONLY** shorten radio button blurb
- [ ] 9. **eligibility index:** **DELETION** remove `Not sure which option is right for you? Please visit [HelpPage](https://dev-benefits.calitp.org/help).`
- [ ] 10. **eligibility start:** cc - **COPY ONLY** add the word `transit` to the headline
- [ ] 11. **eligibility start:** login.gov - **COPY ONLY** add the word `transit` to the headline
- [ ] 12. **eligibility start:** login.gov - **CODE AND COPY** media item - modal link and add new copy about phone number
- [ ] 14. **eligibility start:** ALL flows - payment media item - **COPY ONLY** copy for title
- [ ] 15. **eligibility start:** ALL flows - payment media item - **COPY ONLY** copy for description, with modal link
- [ ] 17. **eligibility start:** ALL flows - **DELETION** remove `Questions about the items above? Please visit our Help Page.`
- [ ] 18. **eligibility confirm:** cc - **DELETION** remove 1 paragraph
- [ ] 19. **enrollment index:** ALL flows - **COPY** change title to `Your eligibility is confirmed! You’re almost there.`
- [ ] 20. **enrollment index:** ALL flows - **DELETION** remove top media item
- [ ] 21. **enrollment index:** ALL flows - **COPY ONLY** payment media item - change copy on LittlePay media item

**Comment by machikoyasuda** [comment]
Questions to ask:
- What does a Veterans flow look like without any modals?
- What copy changes MUST we make for Login.gov and CC, so it fits with Veterans flow? (At the very least, Elig Index radio button tense change, Elig Start title, Enrollment Index - remove the 1st media item)
- Can we remove the 2 different `Not sure which option is right for you? Please visit our [Help Page](https://dev-benefits.calitp.org/help).` links WITHOUT adding the modals back in? Can we deploy this in this state?

**Comment by thekaveman** [comment]
Thank you for this exhaustive list @machikoyasuda. Now that everything is represented in issues and on the Project Board, I'm going to close this issue.
