### ISSUE TITLE
Refactor usage of view models

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1442]
As shown in #1436, adding or moving around copy driven by translations requires changes in multiple places:

* models, to reference the PO entries
* PO files, to hold the translations
* view view models, to get the data into the view

We need to look into how to simplify this, ideally cutting out extraneous view models that already have a corresponding model, and sending that directly to the template instead.

## Plan

After some different iterations, this is the approach we landed on:

* Move all translated strings out of models, and as close to the templates (HTML) as possible
* Use fields in the models to reference template variants when needed (e.g. for TransitAgency and EligibilityVerifier)
* Simplify the views as much as possible: remove usage of viewmodels, create basic dictionary context that has exactly the fields needed for that view/page

## Acceptance Criteria

The following `viewmodels` and helpers are removed:

- [x] `viewmodels.Button` #1562
  - [x] `viewmodels.Button.agency_contact_links` #1521
  - [x] `viewmodels.Button.home` #1522
  - [x] `viewmodels.Button.link` #1521
  - [x] `viewmodels.Button.login` #1498
  - [x] `viewmodels.Button.logout` #1534
  - [x] `viewmodels.Button.primary` #1562
  - [x] `viewmodels.Button.outline_primary` #1562
  - [x] `viewmodels.Button.previous_page` #1562
- [x] `viewmodels.Icon` #1542
- [x] `viewmodels.MediaItem` #1542
- [x] `viewmodels.Modal` #1504
  - [x] `viewmodels.AgencySelector` #1504
- [ ] `viewmodels.Page` #1563
- [x] `viewmodels.ErrorPage` #1536
  - [x] `viewmodels.ErrorPage.user_error`  #1536
  - [x] `viewmodels.ErrorPage.server_error`  #1536
  - [x] `viewmodels.ErrorPage.not_found`  #1536
- [x] `viewmodels.PaymentProcessor` #1502
- [x] `viewmodels.TransitAgency` #1541

**Comment by thekaveman** [comment]
We could move most of what view models are doing to using [Django template tags](https://docs.djangoproject.com/en/4.2/howto/custom-template-tags/#writing-custom-template-tags). This seems like a good approach because:

* Removes need for view model classes, can pass needed data to each tag or get it from `context`
* Moves us closer to the concept of "components", will simplify and clarify templates and help reuse
* Likely simplifies view functions as well
* Tags should be straightforwardly testable

Django makes two types available OOTB:
* [simple tags](https://docs.djangoproject.com/en/4.2/howto/custom-template-tags/#writing-custom-template-tags) return a string to be wrapped by other HTML in a template
* [inclusion tags](https://docs.djangoproject.com/en/4.2/howto/custom-template-tags/#inclusion-tags) use their own named template file, like includes do in the HTML

Django also has a way to write more [advanced custom tags](https://docs.djangoproject.com/en/4.2/howto/custom-template-tags/#advanced-custom-template-tags), probably more than we need for now.

**Comment by machikoyasuda** [comment]
Putting these notes here:

There are 3 places in the new Veteran flow app that requires logic in the `views` with knowledge of `EligibilityVerifier`-specific information:
- Eligibility Start (show 3 bullets vs. 4 bullets in the first identity MediaItem)
- Sign Out link (show Sign Out link or not -- could have some sort of `EligibilityVerifier.supports_signout` boolean on the model) #1456 
- Use `Button.login()` (which sets the button's CSS ID to `login` and specifies a hard-coded fallback text of `Login.gov`)

**Comment by thekaveman** [comment]
We have a pretty solid plan:

* Move all translated strings out of models, and as close to the templates (HTML) as possible
* Use fields in the models to reference template variants when needed (e.g. for `TransitAgency` and `EligibilityVerifier`)
* Simplify the views as much as possible: remove usage of `viewmodels`, create basic dictionary `context` that has exactly the fields needed for that view/page

And some different pieces of this implementation:

* #1489
* #1498
* #1502 
* #1504
* #1517

Considering this closed.

**Comment by thekaveman** [comment]
Blocked: https://github.com/cal-itp/benefits/pull/1563#issuecomment-1650690275
