### ISSUE TITLE
Agency & Eligibility Verifier string variable implementation

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1500]
I'm splitting this ticket out from https://github.com/cal-itp/benefits/issues/1386 and https://github.com/cal-itp/benefits/pull/1499

## Tasks

- [ ] Product / Design: Need to determine the final list of new variables needed, the names of the variables, and fallback / sample values for the variables for both TransitAgency and EligibilityVerifier (Only MST Courtesy Cards).
- [ ] Product: Decide when Agency and EligibilityVerifier variables are to be done. EV is only necessary for when a 2nd agency card flow is added. Agency variables are necessary for when SacRT is launched (to take care of light rail vs. bus difference).
- [ ] Product / Design: Make sure Figma, Google Spreadsheet, and the keys & values in this ticket are aligned.
- [ ] Product: Get, write, (get approved(?)) the actual values for each variable for MST and SacRT in English. Then get it translated into Spanish.
- [ ] Engineering: Add these variables to the TransitAgency model, add the values as msgids
- [ ] Engineering: Use the variables in the new copy

## Current status

- Code status: Engineering is ready to add 1 variable (`transit_type`) for the Home and Agency Index page. #1499 
- Copy status: No variable string copy written for MST or SacRT.

## Potential issues
- MST variable copy has not been written or translated yet. Almost all the MST variable copy and Spanish translation can be inferred from previous copy, except for `fixed route` - we do not have a Spanish translation for `fixed route`.
- SacRT variable copy has not been written or translated yet. Most SacRT variable copy cannot be inferred from previous copy. Don't have key terms like `light rail` translated. `When boarding a SacRT light rail` - is that correct? or should it be `When boarding a SacRT light rail train`, or `light rail car`. Does `for light rail service on fixed routes` even make sense b/c wouldn't non-fixed route be impossible on light rail(?)
- Other questions: Should there be default fallback copy values if we don't have a variable value specified by the agency yet? If so, those need to be written as well.

## New variables on Transit Agency

_These two tables reflect the variables as declared in the Figma/Google Spreadsheet_

Figma, Google | Code variable name | MST | SacRT
-- | -- | -- | --
[transit option \|\| transit type] | `transit_type` | bus | light rail
[action] | `TBD` | reduces | reduces
[rate of discount] | `TBD` | 50% | 50%
[affected service] | `TBD` | fixed route | fixed route
[transportation type] | `TBD` | public transportation | light rail train
[card functionality] | `TBD` | tap this card when you get on and off | tap this card when you get on and off 

Note: The main need for this for MST Veterans launch, after SacRT is deployed. The main difference is the fixed route/bus (MST) vs. light rail (SacRT). All the other information (like reduces, 50%, card action is the same).
- Used in https://github.com/cal-itp/benefits/issues/1472
- Used in https://github.com/cal-itp/benefits/issues/1432

## New variables on EligibilityVerifier

Figma, Google | Code variable name | Courtesy Card | Sample Agency Card
-- | -- | -- | --
[optional qualifier] | `TBD` | Courtesy Card or an MST RIDES Eligibility card |  
[qualifier] | `TBD` | you will need to know the number | you will need to know the number
[qualifier] | `TBD` | The number starts with a number sign (#) followed by five digits. | The number starts with a number sign (#) followed by 12 digits.
[ID number type] | `TBD` | number | number
[identity marker] | `TBD` | last name | last name
[qualifer] | `TBD` | This is a 5-digit number on the front and back of your card. | This is a 12-digit number on the front of your card.
- Used in https://github.com/cal-itp/benefits/issues/1482

Note: These variables aren't truly necessary until we have a 2nd Agency Card (like SBMTD). This change could be done after SacRT/MST Veterans launch.

## How the variables are used throughout the app in general

The `Copy with variables` is copied directly from Figma/Google Spreadsheet. The `Final copy` is taken from 
Figma's Benefits Sample Agency.

### Eligibility Index
- Copy with variables: `Cal-ITP doesn’t save any of your information. All [short name] transit benefits [action] by [rate of discount] for [affected service] on [transit options].`

- Final copy: `Cal-ITP doesn’t save any of your information. All CST transit benefits reduce fare by 50% for bus service on fixed routes.` ... or `All MST transit benefits reduce fare by 50% for fixed routes on public transportation.` Figma has both examples on it.

### Enrollment Success
- Copy with variables: `You were not charged anything today. When boarding a [short name] [transportaton type], [card functionality -  e.g. tap this card when you get on and off the bus] and you will be charged a reduced fare. You will need to re-enroll if you choose to change the card you use to pay for transit service.` (The `transporaton` typo is part of the Figma/Google Spreadsheet).

- Final copy: `You were not charged anything today. When boarding a CST bus, tap this card and you will be charged a reduced fare. You will need to re-enroll if you choose to change the card you use to pay for transit service.`

### Agency Card flow
<img width="498" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/5e0b3298-b0ca-44c6-ab43-a6b83a787103">

<img width="445" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/657612b7-442e-44d9-9d90-a3d370072edb">

**Comment by machikoyasuda** [comment]
Hey @indexing - I had questions about how the variable strings need to be implemented for this upcoming sprint, and for sprints after that. 

- For Sprint 7, what are Engineers supposed to do with regards to un-written and un-translated string variables for MST Veterans/Login.gov, SacRT Login.gov and MST CC? There are a few options: Don't do anything at all -- don't add a variable or a variable fallback, just put TODO TODO in the copy itself. Like the Enrollment Success page would read, for example, `When boarding a MST [transportaton type], [card functionality -  e.g. tap this card when you get on and off the bus] and you will be charged a reduced fare.` OR - to add the variables, but don't put any values in them yet. If this is the case, then we'll need to know the exact names of each variable key -- right now, the Figma app/Google Spreadsheet has a few keys that sound similar (like transit_option, transit_type and transportation_type - can those be combined or do we really need all those?). 

- For this specific sentence, I was asking @srhhnry how this sentence is intended to be for SacRT:

`Cal-ITP doesn’t save any of your information. All CST transit benefits reduce fare by 50% for bus service on fixed routes.` But on the 2nd tab of our main Google Spreadsheet, I saw this as an example: `
"All CST transit benefits reduce fare by 50% for bus service on fixed routes."` The prepositional phrases are switched in order, and it makes it confusing what exactly `affected_service` and `transit_options` map to. Also, how would this sentence work for light rail? Because light rail is by default always fixed route, so having that extra `on fixed route` doesn't really make sense.

**Comment by machikoyasuda** [comment]
Update: DO NOT make new variables. Will be using new template flow instead.
