### ISSUE TITLE
Refactor msgids in PO files

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1571]
[Historically](https://github.com/cal-itp/benefits/pull/11), we've treated the `msgid` in PO files as more of an identifier for the text of the `msgstr`. This is not the default behavior of language files in Django, however: https://docs.djangoproject.com/en/4.2/topics/i18n/translation/

More typically, the `msgid` is the text copy in the _default language_ of the site, and the `msgstr` is used to override the default in different languages.

We continue looking for ways to simplify management of the app copy, we should refactor our PO files to follow this standard model.

Needs [#1581](https://github.com/cal-itp/benefits/issues/1581) to be completed first.

## Todo

- [x] In the _English_ PO file, replace all `msgid` with the corresponding text in the `msgstr`
- [x] In the app, replace all references to a prior `msgid` with the corresponding English text
- [x] ~Delete the _Spanish_ PO file~ This isn't necessary
- [x] Run `bin/makemessages.sh` to regenerate the Spanish PO with new English `msgid` and blank `msgstr`
