### ISSUE TITLE
Create a QA Checklist for Design

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1609]
Create a QA Checklist for Design as sign-off documentation for dev. This checklist to include:

- [x] List of resources for creating test accounts in Login.gov and (if applicable) ID.me
- [x] Page by page considerations, such as placement of any novel elements (e.g. success page has an illustration 
- [x] Site-wide considerations, such as typography, color, navigation, grammatical conventions
- [x] How to communicate findings to Dev

**Comment by srhhnry** [comment]
[Checklist for benefits veteran flow](https://docs.google.com/document/d/1PlcoyMNSkwT2VJpPfmuS-cun4snYV5Bvse5zrYKWG08/edit?usp=sharing)

Will use as a template for others

**Comment by srhhnry** [comment]
Added the checklist to #1582
