### ISSUE TITLE
Create app configuration for SBMTD+Agency card (Mobility Pass)

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1664]
## Tasks

- [x] Define `EligibilityType` for "SBMTD Mobility Pass"
- [x] Define `EligiblityVerifier` using MST CC as an example
  - [x] Need a per-verifier `SERVER_PUBLIC_KEY_URL` variable
- [x] Define necessary includes/templates
- [x] Define form `SBMTDMobilityPass` with configuration (labels, helper, validation, etc.)
- [x] Update SBMTD `TransitAgency`
- [x] Update all relevant copy for English and Spanish

## Acceptance criteria

- [x] SBMTD user sees an option for "Mobility Pass" on the Eligibility Index page
- [x] Selecting "Mobility Pass" shows more info on the Eligibility Start page
- [x] Continuing shows the Eligibility Confirm page with rendered form / details
- [x] English and Spanish match [`SBMTD` tab of spreadsheet](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit#gid=536435981)
- [x] Help page update
- [x] Submitting the form with sample data (e.g. against a local `server`) correctly verifies eligible and ineligible users

**Comment by machikoyasuda** [comment]
## Mobility Pass validation details
- 4 digits, numbers only
- Last name

**Comment by thekaveman** [comment]
Blocking this until we have a deployment of the Eligibility Server for SBMTD.

**Comment by thekaveman** [comment]
Unblocking for Sprint 11, we can get started on this now that we are close to having a server live.

**Comment by machikoyasuda** [comment]
@thekaveman @angela-tran I'm thinking through this ticket. To get `Submitting the form with sample data (e.g. against a local server) correctly verifies eligible and ineligible users` to work correctly, I'll need to add 4-digit ID subs and name combinations to Eligibility Server (https://github.com/cal-itp/eligibility-server/blob/64e421d75306784945be7bd7fc57ee6ce1ecdd66/data/server.csv#L4 / https://github.com/cal-itp/eligibility-server/blob/64e421d75306784945be7bd7fc57ee6ce1ecdd66/data/server.json), right?

**Comment by thekaveman** [comment]
@machikoyasuda yep! Except let's just forget about the JSON version (https://github.com/cal-itp/eligibility-server/issues/348).

We also need the sample data to have the correct `type` value: `mobility_pass`.
