### ISSUE TITLE
[TRACKING] Refactor models to more explicitly represent user flow

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1666]
Initial proposal for a model refactor is on a new tab in the [Benefits admin configuration](https://docs.google.com/spreadsheets/d/1lPp_LJTfJoWCyOkRC4RaljABGG_jPWOgm4gaAHJigMU/edit?gid=2013104124#gid=2013104124) spreadsheet. The idea here is just to reorganize the existing data without introducing any new logic or broader changes.

Highlights:

* Reduced total models from `6` to `5`
* Reduced total fields from `66` to `62`
* Renamed `AuthProvider` to `ClaimsProvider`
* Combined most fields from `EligibilityType` and `EligibilityVerifier` into new model `EnrollmentFlow`
* Moved flow-specific API data from `ClaimsProvider` to `EnrollmentFlow`
* Renamed `PaymentProcessor` to `TransitProcessor`
* Moved agency-specific API data from `TransitProcessor` to `TransitAgency`

## Pre-conditions

- [x] We agree on the model / field refactors
- [x] ~#2228~
- [x] We know each place in the code where a given model and field is used
  - Not necessarily line-by-line, but e.g. _"`enrollment.views` uses these models: X, Y, Z"_
- [x] #2229
- [x] #2230
- [x] #2231

## Acceptance criteria

- [x] ~`PemData` model refactors~ N/A
- [x] #2233
- [x] #2235
- [x] #2234
- [x] #2236
  - [x] #2237
  - [x] #2238
  - [x] #2282
  - [x] #2283

## Additional context

Building on and informed by #1442, #1564, #1662

~It might be useful to introduce type hints in method signatures as part of this refactor; doing so will help with catching mistakes and ensuring all models/fields are covered. _EDIT: see #2228_~

**Comment by thekaveman** [comment]
The bulk of the refactor work is now done.

Putting on `Pause` until we can come back to the analytics work.
