### ISSUE TITLE
Refactor handling of secret model fields

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1847]
Implementation plan from #1764

## Implementation plan

- [x] Implement a simple helper script in the spirit of [this one in `data-infra`](https://github.com/cal-itp/data-infra/blob/main/packages/calitp-data-infra/calitp_data_infra/auth.py); use [Azure's python libraries](https://learn.microsoft.com/en-us/python/api/overview/azure/keyvault-secrets-readme?view=azure-python&source=recommendations) to read a value from a Key Vault by secret name. Ensure the Key Vault / environment (e.g. `dev`, `test`, `prod`) is not hardcoded; create a setting from an environment variable or similar. #1859
- [x] [Create a custom Django field type](https://docs.djangoproject.com/en/5.0/howto/custom-model-fields/) that inherits from `models.TextField`. The default field implementation stores the name of the secret. #1874
- [x] Using the [field mapping spreadsheet](https://docs.google.com/spreadsheets/d/1lPp_LJTfJoWCyOkRC4RaljABGG_jPWOgm4gaAHJigMU/edit#gid=176385027), update all secret fields to have this new field type. Update the field names to include a `_secret_name` postfix #1874
- [x] Add new properties to each model that use the helper script above and the `_secret_name` field value to get the actual value of the secret. These properties should be named the same as the original (pre-refactor) secret field (e.g. without the `_secret_name` postfix) #1874
