### ISSUE TITLE
Make a Release: 2024.03.1

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1926]
### Release manager

@angela-tran

### Smoke tester

@thekaveman

### Release version

2024.03.1

### What type of release is this?

Regular

### Regular release checklist

- [x] Ensure the `dev` branch and secrets are up to date
- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into `dev`, merge #1927
- [x] Ensure `test` secrets are up to date
- [x] Open another PR from `dev` to `test`, merge #1928
- [x] QA the app in test
- [x] Ensure `prod` secrets are up to date
- [x] Open a PR for the `test` branch into `prod`, merge #1929 
- [x] Smoke Test the app in prod
- [x] Confirm acceptance of Smoke Tests by adding a comment to this issue
- [x] Tag the release on the `prod` branch, push the tag to GitHub (see [docs](https://docs.calitp.org/benefits/deployment/release/#5-tag-the-release) for commands)
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by thekaveman** [comment]
Accepting smoke tests for the following flows:

* MST
  * Older Adult
  * Veteran
  * Courtesy Cards
* SBMTD
  * Older Adult
  * Mobility Pass

**Comment by angela-tran** [comment]
Thanks @thekaveman !
