### ISSUE TITLE
Back Office API configuration for test and prod

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1937]
## Todo `test`

- [x] Add the new `client_secret` secrets in KeyVault
- [x] Update the `PaymentProcessor` instances in the Admin with new secret names and non-secret config
- [x] Delete the old cert-based secrets in KeyVault
- [x] Delete the old `PemData` instances in the Admin

## Todo `prod`

- [x] Add the new `client_secret` secrets in KeyVault
- [x] Update the `PaymentProcessor` instances in the Admin with new secret names and non-secret config
- [x] Delete the old cert-based secrets in KeyVault
- [x] Delete the old `PemData` instances in the Admin

_Originally posted by @thekaveman in https://github.com/cal-itp/benefits/issues/1905#issuecomment-1986244390_

**Comment by thekaveman** [comment]
All secrets and model updates have been made in both `test` and `prod` and the apps are back online and functional.
