### ISSUE TITLE
Release 2024.03.2: Back Office API refactor

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1943]
### Release manager

@angela-tran

### Smoke tester

@thekaveman

### Release version

2024.03.2

### What type of release is this?

Regular

### Regular release checklist

- [x] Ensure the `dev` branch and secrets are up to date
- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into `dev`, merge #1945
- [x] Ensure `test` secrets are up to date
- [x] Open another PR from `dev` to `test`, merge #1946
- [x] QA the app in test
- [x] Ensure `prod` secrets are up to date
- [x] Open a PR for the `test` branch into `prod`, merge #1947
- [x] Smoke Test the app in prod
- [x] Confirm acceptance of Smoke Tests by adding a comment to this issue
- [x] Tag the release on the `prod` branch, push the tag to GitHub (see [docs](https://docs.calitp.org/benefits/deployment/release/#5-tag-the-release) for commands)
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed

## Additional release tasks

- [x] Pin version of [`littlepay`](https://github.com/cal-itp/littlepay) library #1944
- [x] #1937

**Comment by thekaveman** [comment]
Smoke testing in `prod` was successful

## Flows tested

* MST: Older Adult, Courtesy Cards -- got the expected "Unable to verify eligibility" response
* SBMTD: Older Adult, Mobility Pass -- got the expected "Unable to verify eligibility" response

**Comment by angela-tran** [comment]
🎉 🏢
