### ISSUE TITLE
test and prod configuration for CalFresh

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1978]
## Todo `test`
- [x] Update `help_template` on `EligibilityVerifier` instances
   - [x] `core/includes/help--mst-courtesy-card.html` for MST eligibility server verifier
   - [x] `core/includes/help--sbmtd-mobility-pass.html` for SBMTD eligibility server verifier
   - [x] `core/includes/help--calfresh.html` for any CalFresh verifiers

## Todo `prod`
- [ ] Update `help_template` on `EligibilityVerifier` instances
   - [x] `core/includes/help--mst-courtesy-card.html` for MST eligibility server verifier
   - [x] `core/includes/help--sbmtd-mobility-pass.html` for SBMTD eligibility server verifier
   - [ ] `core/includes/help--calfresh.html` for any CalFresh verifiers

**Comment by thekaveman** [comment]
Blocked by #2189

**Comment by thekaveman** [comment]
We can close this. We'll need to configure everything about the CalFresh flow in production when we are ready with an agency.
