### ISSUE TITLE
test and prod configuration for Agency Card flow copy improvements

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2022]
## Todo `test`

- [x] Update Courtesy Card and Mobility Pass eligibility types so their enrollment index template is `enrollment/index--agency-card.html`

Due to [model changes](https://github.com/cal-itp/benefits/blob/8b56df4612c37a2dea18ffd6740da172f2699271/benefits/core/migrations/0011_move_enrollment_success_template_field.py) in #2067: 
- [x] Update MST Courtesy Card  eligibility type so its enrollment success template is `enrollment/success--mst-courtesy-card.html`.
- [x] Update SBMTD Mobility Pass eligibility type so its enrollment success template is `enrollment/success--sbmtd-mobility-pass.html`.
- [x] Update MST Senior Discount and Veteran Discount eligibility types so their enrollment success template is `enrollment/success--mst.html`.
- [x] Update SBMTD Senior Discount eligibility type so its enrollment success template is `enrollment/success--sbmtd.html`.
- [x] Update SacRT Senior Discount eligibility type so its enrollment success template is `enrollment/success--sacrt.html`.

Due to [model changes in #2053](https://github.com/cal-itp/benefits/pull/2053/files#diff-cea7b783aff074158a2a778fb934f1b9d3e846d89346aaa9b9f7e5ab30169c37):
- [x] Update `unverified_template` on Eligibility Verifiers:
   - [x] MST Courtesy Card: `eligibility/unverified--mst-courtesy-card.html`
   - [x] SBMTD Reduced Fare Mobility ID: `eligibility/unverified--sbmtd-mobility-pass.html`

## Todo `prod`

- [x] Update Courtesy Card and Mobility Pass eligibility types so their enrollment index template is `enrollment/index--agency-card.html`

Due to [model changes](https://github.com/cal-itp/benefits/blob/8b56df4612c37a2dea18ffd6740da172f2699271/benefits/core/migrations/0011_move_enrollment_success_template_field.py) in #2067: 
- [x] Update MST Courtesy Card  eligibility type so its enrollment success template is `enrollment/success--mst-courtesy-card.html`.
- [x] Update SBMTD Mobility Pass eligibility type so its enrollment success template is `enrollment/success--sbmtd-mobility-pass.html`.
- [x] Update MST Senior Discount and Veteran Discount eligibility types so their enrollment success template is `enrollment/success--mst.html`.
- [x] Update SBMTD Senior Discount eligibility type so its enrollment success template is `enrollment/success--sbmtd.html`.
- [x] Update SacRT Senior Discount eligibility type so its enrollment success template is `enrollment/success--sacrt.html`.

Due to [model changes in #2053](https://github.com/cal-itp/benefits/pull/2053/files#diff-cea7b783aff074158a2a778fb934f1b9d3e846d89346aaa9b9f7e5ab30169c37):
- [x] Update `unverified_template` on Eligibility Verifiers:
   - [x] MST Courtesy Card: `eligibility/unverified--mst-courtesy-card.html`
   - [x] SBMTD Reduced Fare Mobility ID: `eligibility/unverified--sbmtd-mobility-pass.html`

**Comment by angela-tran** [comment]
I created this because for a bit I forgot how the Eligibility Index page works and thought it was based off something in the database 😅 

Keeping this around in case we end up having any configuration that needs to be updated from tickets on #2006. We can close it if it ends up there's no configuration to update.

**Comment by thekaveman** [comment]
@lalver1 would you please update the checklist above for any config changes we need to make after #2067 is merged?

**Comment by thekaveman** [comment]
ping @lalver1: https://github.com/cal-itp/benefits/issues/2022#issuecomment-2120570515
