### ISSUE TITLE
New `System enrollment error` page

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2032]
![image](https://github.com/cal-itp/benefits/assets/25497886/7a9ce18e-0440-4262-ba48-29b51eeec1e9)

## Acceptance Criteria

Front-end design implementation:
- [x] Updated headline
- [x] Updated body copy
- [x] Updated CTA button (Login.gov and non-login.gov variants - “Sign out of Login.gov” and “Return home”)
   - [x] Login.gov CTA variant signs them out and takes them back to agency index
   - [x] Non-login.gov CTA variant takes them back to the agency index

Back-end logic
- [x] System enrollment errors should still cause Sentry notifications and Amplitude events to be sent
- [x] 500-level HTTP errors during linking of funding-source and group should show system enrollment error - #2088 
- [x] Errors during the acquisition of card tokenization access token should send user to an error page - Javascript in `enrollment/index.html` will need to know where to send user
   - [x] 500-level HTTP errors show system enrollment error page - #2089
   - [x] 400-level HTTP errors and any other types of errors show server error page - #2117
- [x] `onError` callback in tokenization function needs to redirect
   - [x] to system enrollment error page if 500-level HTTP error - #2120
   - [x] to server error page if 400-level HTTP error - #2120

## Additional context

- Handles the case of our connection to Littlepay being broken e.g. because Littlepay’s system is down or returning errors.

**Comment by angela-tran** [comment]
All subtasks have been completed
