### ISSUE TITLE
[TRACKING] Transit app banner campaign: metrics to track engagement

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#2036]
We are supporting an MST campaign to promote digital benefits enrollment via [Transit app](https://transitapp.com/). Before we launch, we want to design and implement metrics to help us understand the effectiveness of this new exploration in promotion. 

## Issue list

- [x] #2034
- [x] #2035

## Acceptance Criteria

- [x] Product can assess effectiveness of the campaign using metrics in Amplitude.
- [x] We can generate multiple unique URLs to associate with specific banners that Transit app will display to MST riders.
- [x] Product can track engagement from each URL: 
  - count of visits from each the banner
  - events the user triggered beginning at the app landing page
  - count of successful enrollments originating from banner.

**Comment by indexing** [comment]
All necessary charts are in place in Amplitude: https://app.amplitude.com/analytics/compiler/chart/lhg1stku/edit/2sv6hvnd
