### ISSUE TITLE
Release agency card UX updates, error UX updates, UTM code handling

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2098]
### Release manager

@lalver1

### Smoke tester

@angela-tran

### Release version

2024.05.1

### What type of release is this?

Regular

### Regular release checklist

- [x] Ensure the `dev` branch and secrets are up to date
- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into `dev`, merge #2099 
- [x] Ensure `test` secrets are up to date
- [x] Open another PR from `dev` to `test`, merge #2100 
- [x] QA the app in test
- [x] Ensure `prod` secrets are up to date
- [x] Open a PR for the `test` branch into `prod`, merge #2101 
- [x] Smoke Test the app in prod
- [x] Confirm acceptance of Smoke Tests by adding a comment to this issue
- [x] Tag the release on the `prod` branch, push the tag to GitHub (see [docs](https://docs.calitp.org/benefits/deployment/release/#5-tag-the-release) for commands)
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes to link back to this Release process issue
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by thekaveman** [comment]
Confirmed enrollment success in `test` for:

* MST Veteran
* SacRT Older Adult

**Comment by angela-tran** [comment]
Confirmed enrollment success in `test` for
 - MST Older Adult

I'm seeing an issue with SBMTD Older Adult where during enrollment, I keep seeing the user enrollment error page:
![image](https://github.com/cal-itp/benefits/assets/25497886/a689dae2-63d0-4c0f-af39-727386bd9d48)

**Comment by lalver1** [comment]
Confirmed enrollment success in `test` for
 - MST Courtesy Card

**Comment by thekaveman** [comment]
> Confirmed enrollment success in `test` for
> 
>     * MST Older Adult
> 
> 
> I'm seeing an issue with SBMTD Older Adult where during enrollment, I keep seeing the user enrollment error page: ![image](https://private-user-images.githubusercontent.com/25497886/330898412-a689dae2-63d0-4c0f-af39-727386bd9d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3OTQ3NTIsIm5iZiI6MTcxNTc5NDQ1MiwicGF0aCI6Ii8yNTQ5Nzg4Ni8zMzA4OTg0MTItYTY4OWRhZTItNjNkMC00YzBmLWFmMzktNzI3Mzg2YmQ5ZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE3MzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMWFjZTE2NzUwZTMyZjFhOTcwZjBhNGMyNDcwZWJhZjdmOGRkYTFhNTE1YzkxZGFjYTdmMDNhNmRmMWRlOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4XdemGbu_HXPLtLygXaRdinoI-wOHnK-8R4kFYH3U_w)
> 
> Debugging in the dev console shows we're hitting the `onVerificationFailure` callback with a response of
> 
> ```
> Object { status: 200, message: "TOKENISATION FAILED" }
> ```

We'll have to reach out to Littlepay about this error -- it seems like a problem with SBMTD in Littlepay QA specifically.

I configured `test` to point to Littlepay prod for SBMTD and was able to enroll for Older Adult.

**Comment by thekaveman** [comment]
Smoke testing in `prod` complete, got the expected result "Eligibility could not be verified" for the following flows:

- MST Older Adult
- MST Veteran
- MST Courtesy Cards
- SBMTD Older Adult
- SBMTD Reduced Fare Mobility ID
