### ISSUE TITLE
Release error UX updates, refactored claims handling, refactored Azure deployments and data persistence

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2145]
### Release manager

@thekaveman

### Smoke tester

@angela-tran

### Release version

2024.06.1

### What type of release is this?

Regular

### Regular release checklist

- [x] Merge #2144 
- [x] Update Terraform pipeline version / close #2118
- [x] Update the version of `littlepay==2024.06.1` #2147 
- [x] #2134 
- [x] Ensure the `dev` branch and secrets are up to date
- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into `dev`, merge #2148
- [x] `dev`: Update `claim` and `scope`, test Login.gov
- [x] Open another PR from `dev` to `test`, merge #2175
- [x] Use checklist in #2153 for `test` environment
- [x] `test`: Update `claim` and `scope`
- [x] #1978
- [x] #2022
- [x] QA the app in test
- [x] Open a PR for the `test` branch into `prod`, merge #2182
- [x] Use checklist in #2153 for `prod` environment
- [x] #1978
- [x] #2022
- [x] `prod`: Update `claim` and `scope`
- [x] Smoke Test the app in prod
- [x] Confirm acceptance of Smoke Tests by adding a comment to this issue
- [x] Tag the release on the `prod` branch, push the tag to GitHub (see [docs](https://docs.calitp.org/benefits/deployment/release/#5-tag-the-release) for commands)
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes to link back to this Release process issue
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by thekaveman** [comment]
Blocked until we can solve the issue with the `dev` database being locked and preventing Admin logins.

**Comment by angela-tran** [comment]
We should also do #1978 as a part of this release so we don't break the Help page. 

Even though the CalFresh expiry functionality isn't in this release, the CalFresh template changes are.

**Comment by thekaveman** [comment]
We QA'd and verified in the `test` environment:

- [x] Integer claims for Older Adult and Veteran
- [x] Help pages for MST, SacRT, SBMTD
- [x] Eligibility fail and enrollment success for MST Courtesy Cards
- [x] Eligibility fail for SBMTD Reduced Fare Mobility ID
- [x] Enrollment success for MST and SacRT Older Adult
- [ ] Enrollment success for SBMTD Older Adult: _SBMTD API with Littlepay having some issues_
- [ ] Enrollment success for SBMTD Reduced Fare Mobility ID: _SBMTD API with Littlepay having some issues_

**Comment by angela-tran** [comment]
I verified in the `prod` environment:

- [x] Eligibility fail for MST Courtesy Cards
- [x] Eligibility fail for SBMTD Reduced Fare Mobility ID

which means Benefits was able to connect to both eligibility servers ✅

**Comment by thekaveman** [comment]
I verified in the `prod` environment:

- [x] Eligibility fail for MST Older Adult
- [x] Eligibility fail for MST Veteran
- [x] Eligibility fail for SBMTD Older Adult

which means Benefits was able to connect to IdG using the new claims format :heavy_check_mark:

**Comment by thekaveman** [comment]
During smoke testing, we uncovered a bug that prevents users from signing out of their Login.gov session.

Since this a very low impact bug, we'll get it fixed and released later this week as part of #2167
