### ISSUE TITLE
[TRACKING] Model refactor: create a new `EnrollmentFlow` model

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2236]
This model will combine most fields from the existing `EligibilityType` and `EligibilityVerifier` models.

## Acceptance criteria

Mostly in order of how this should be done.

- [x] #2238 
- [x] #2237 
- [x] #2282
- [x] #2283
- [x] A new model exists called EnrollmentFlow with all fields as documented (and in the same order) in the [refactor proposal tab of the spreadsheet](https://docs.google.com/spreadsheets/d/1lPp_LJTfJoWCyOkRC4RaljABGG_jPWOgm4gaAHJigMU/edit?gid=2013104124#gid=2013104124)
- [x] Existing Django config data is migrated
- [x] Docs are updated

## Impact on the code

- [ ] [Code search for `eligibility` in the repo](https://github.com/search?q=repo%3Acal-itp%2Fbenefits+eligibility&type=code)
- [ ] [Code search for `verifier` in the repo](https://github.com/search?q=repo%3Acal-itp%2Fbenefits+verifier&type=code)

## Impact on existing data

Documented in the issues tracked above under _Approach_.

## Impact on analytics

- [ ] `EligibilityType.name` is logged in analytics using the [`eligibility_types` event property](https://github.com/cal-itp/benefits/blob/main/benefits/core/analytics.py#L56) and [user property](https://github.com/cal-itp/benefits/blob/main/benefits/core/analytics.py#L71) -- this is the primary field used in chart filters and groupings
- [ ] `EligibilityType.group_id` is logged in analytics using the [`payment_group` event property](https://github.com/cal-itp/benefits/blob/main/benefits/enrollment/analytics.py#L16)
- [ ] `EligibilityVerifier.name` is logged in analytics using the [`eligibility_verifier` event property](https://github.com/cal-itp/benefits/blob/main/benefits/core/analytics.py#L57) and [user property](https://github.com/cal-itp/benefits/blob/main/benefits/core/analytics.py#L72)
- [ ] Some of these changes will need to be addressed in this ticket as the corresponding fields will no longer exist
- [ ] #2248 is a follow-up

## Impact on Admin permissions

Documented in the issues tracked above under _Approach_.
