### ISSUE TITLE
[TRACKING] Agency card mailer campaign

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#2260]
## Overview

The Santa Barbara Metropolitan Transit District (SBMTD) announced earlier this year that eligible riders can utilize Cal-ITP Benefits to enroll in their discount fare program. By registering their contactless debit or credit card, riders will automatically receive reduced fares when they tap-to-pay. The app currently supports enrollment for two rider groups at SBMTD: older adults (65+) and those who have qualified for a Reduced Fare Mobility ID. This promotion will focus solely on enrolling riders who currently have a Reduced Fare Mobility ID.

We plan to contact existing Reduced Fare Mobility Pass ID holders using a USPS mail campaign. SBMTD will be the first to use this mailer, but it needs to be designed for easy adaptation by other transit operators. For example, Monterey-Salinas Transit (MST), which has around 4000 enrollees in a similar discount fare program, may also utilize this mailer to boost new enrollments.

## Deliverables

- [x] Write a design brief for the mailer design. ([Design Brief](https://doc.clickup.com/8631512/d/h/87d6r-16014/ae8dd2986e293f7))
- [x] Procure mailer designs from agency. 
- [x] Establish short URL that directs users to the enrollment flow. (see design brief)
- [x] Create tracking URL for a QRCODE to be printed on the mailer. (see design brief)
- [x] Create tracking URL for the short URL to be printed on the mailer. (see design brief)
- [x] #2252
![Screenshot 2024-07-31 at 4 15 23 PM](https://github.com/user-attachments/assets/4f674df9-c830-4b05-93f1-06a23f892ccf)

**Comment by indexing** [comment]
All technical work for the campaign is complete.
