### ISSUE TITLE
Medicare cardholder: configure flow in `test` for CST

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2357]
Related to #2356

## Acceptance criteria

- [x] A new `EnrollmentFlow` instance is created via the `test` Admin
- [x] The new flow's system name is `medicare`
- [x] The new flow is configured with appropriate IdG connection, and scope and claim #2364
- [x] The new flow is configured with templates created by related issues
  - [x] #2350
  - [x] ~#2351~ used in the radio button template, doesn't need to be configured on the model
  - [x] #2352
  - [x] #2358
  - [x] #2414 
- [x]  The new flow is configured with a label, the copy of which matches the label from `selection_label_template`
- [x] The new flow is configured with a group ID for the group created for #2356 
- [x] The new flow is added to the CST transit agency
- [x] The new flow is first in the list of all CST flows (show it shows up first on the `eligibility:index` page)
- [x] The new flow confirms eligibility using a valid sample Medicare.gov account
