### ISSUE TITLE
[TRACKING] Automated smoke testing

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2504]
As a part of our release process, we perform smoke tests after deploying to the production app instance (see [the step](https://github.com/cal-itp/benefits/blob/main/.github/ISSUE_TEMPLATE/release.yml?plain=1#L99) in our release issue template: `Smoke Test the app in prod`). 

It would be nice to automate this, and [Playwright](https://playwright.dev) seems like a good tool for doing so.

## Acceptance Criteria

- [ ] Figure out a way for developers to run Playwright easily
- [ ] Write a Playwright test for each test listed in the [Benefits Smoke Testing](https://docs.google.com/document/d/1ADXWW4mfLJwLKVqtVemPNX9yTqYKqIWfCz1DipAU02g/edit?usp=sharing) Google Doc
   - [ ] If it is difficult or not possible to automate certain tests, document the reason
- [ ] Set up GitHub workflow to run Playwright against dev, test, or prod when manually triggered
- [ ] (Optional) Figure out a way for developers to use Playwright tools (trace viewer, inspector, headed mode)

## Related, but separate

- [ ] Set up GitHub workflow to run Playwright against local instance for pull requests
- [ ] Update Benefits Smoke Testing Google Doc to include SacRT flows
- [ ] Move Benefits Smoke Testing Google Doc contents into a page on our documentation site
