### ISSUE TITLE
Refactoring data model to handle multiple flows

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#253]
**Date:** November - December, 2021
**Deciders:** @angela-tran @thekaveman @machikoyasuda 

The next phase of development for this project will require major changes to the way an eligibility/enrollment flow is defined. This is a log of architectural and process decisions made, along with a list of GitHub issues and associated pull requests for this specific architectural refactoring.
 
- Related tickets and pull requests: Initial proposal - https://github.com/cal-itp/benefits/pull/230

## Status
_Proposed and initial work in progress_

## Context

> At present these views are responsible for composing what becomes the UI (text content, forms, buttons, etc.) to send to the template for rendering. We'd like that composition to be specified in the configuration data, to allow the views to make decisions and act on the configuration without having to necessarily "know" what any given configuration is/says.

### Helpful readings

- https://docs.djangoproject.com/en/3.2/ref/class-based-views/generic-display/#detailview
- https://ccbv.co.uk/
- https://django-modeltranslation.readthedocs.io/en/latest/

## Unknowns

1. How to handle forms?
2. How do the views interact with these new models?
3. Can we send these models directly to the template for rendering? Any gotchas?
4. What if any text content doesn't move into a Django db/model system? Do we still need `.po` files?

### Architectural decisions:
1. Take this initial draft https://github.com/cal-itp/benefits/pull/230 and keep working on it, iteratively.

### Process decisions:
1. Complete the work in a long-running feature branch. Keep the feature branch updated with the latest `dev` branch. This means the work in this branch is _not_ expected to be merged into `dev` during this development and testing time.
2. Any hot fix branches that are merged into `dev` should also be merged into this feature branch, with a separate pull request.

### Breaking down the work into smaller pieces:
- [ ] Refactor `views.py` to have a single function that uses a subclass of `DetailsView` that takes the URL slug and looks up the right `Page` model. Updates `urls.py`.
  - [ ] `core`
  - [ ] `eligibility`
  - [ ] `enrollment`
 - [ ] Refactor forms to implement their own POST logic
 - [ ] Refactor forms to use i18n messages from database

**Comment by angela-tran** [comment]
See https://github.com/cal-itp/benefits/pull/265 for some investigation I did on the viability of the first bullet under "**Breaking down the work into smaller pieces**"

**Comment by thekaveman** [comment]
Closing in favor of #317
