### ISSUE TITLE
Go live checklist for Nevada County

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2553]
This task documents a two-phase go live for Nevada County.

## Phase 1: Validation testing

This configuration occurs in `test`.

- [x] [Link additional products to sample group](https://github.com/cal-itp/benefits/issues/2553#issuecomment-2515814813)
- [x] Create a new `TransitProcessor` instance with details for the _live_ system
- [x] Ensure the Nevada County `nevco-payment-processor-client-secret` is updated
- [x] Ensure the Nevada County agency is up to date with this `TransitProcessor` reference and config data
- [x] Ensure a flow for `Older Adult` is configured for Nevada County, see [group details below](https://github.com/cal-itp/benefits/issues/2553#issuecomment-2515814813)
- [x] Confirm that you can successfully go through the flows with sample user and _real payment card details_

## Phase 2: Production

This configuration occurs in `test`.

- [x] Update the Nevada County `nevco-payment-processor-client-secret`, go back to the QA value
- [x] Disassociate the _live_ `TransitProcessor` from the Nevada County agency, go back to the original QA `TransitProcessor`
- [x] Update the `Older Adult` flow to remove the sample group ID, go back to group ID from QA `1ad3c030-70b6-4948-b417-40d332c58a96`

This configuration occurs in `prod`.

- [x] Create the Nevada County agency; do not mark as Active yet
- [x] Ensure a flow for `Older Adult` is configured for Nevada County, [group details below](https://github.com/cal-itp/benefits/issues/2553#issuecomment-2522117799)
- [x] Ensure a flow for `Medicare` is configured for Nevada County, [group details below](https://github.com/cal-itp/benefits/issues/2553#issuecomment-2522117799)
- [x] Activate Nevada County

**Comment by o-ram** [comment]
For testing purposes, a `Test Group` has been set up in the Littlepay production portal and the "senior" product suite will be associated to the group.

**Test Group ID**: `1ab565da-a617-4cd0-ac5c-6167540bc274`

The following Product IDs below should be associated to it.

**Discount Product ID**: `09d8bef8-3f44-48ab-8e60-e8a5b1f3d2e2`
**Discount Time cap ID**: `f61eb087-5b4e-447f-ba8e-48852e4e826f`
**Discount Day cap ID**: `2ff9ea8c-73c3-4667-bc33-81b8ee1a2bd5`
**Discount Week cap ID**: `e485db41-9150-43d7-b573-bc14d4eb0244`
**Discount Month cap ID**: `a48d8cdc-460b-4828-acae-478be42f9b9b`

Littlepay won't let me associate a newly created group to an already created product for some reason, @angela-tran @thekaveman are you able to make this product<>group association on your end? (example [image](https://drive.google.com/file/d/1Ff52QimkJaiduOC5lHOj9ZqLSMl5Kerz/view?usp=sharing), the area to edit the group associations is greyed out)

I've pulled all product and group IDs (senior 65+, Medicare, etc) that will be needed for Nevada to go live, but will put those in a different comment so it is clear what is needed for testing.

**Comment by thekaveman** [comment]
@o-ram thank you!

Are we testing only `Older Adult` for the production validation? Are the discount products the same for `Medicare`?

**Comment by o-ram** [comment]
As of now, we have only planned to test `Older Adult` for production validation. The discount products for the `Medicare` group do have different product IDs (so the transaction data can drill down into rider metrics for different discount groups), but they are exactly the same as the Older Adult ones in terms of fare structure/content. So, if the older adult products work, the Medicare ones should as well. 

That said, I could push for doing testing for the Medicare group as well if that would be the preference.

Here is the information for the additional (non-test) groups:

**Medicare Group ID**: `d8dccb19-cef5-43ef-a97e-0444a6a7d0015`.

- This group ID should _already_ have all of the following product IDs associated to it:

  - **Discount Product ID**: `9a21a110-6f5e-4799-b6ce-2d7fdfa9f622`
  - **Time cap ID**: `1bd0b18b-620a-41df-92b9-18c625102bcf`
  - **Day cap ID**: `02255f33-ddf0-4ac9-a134-fd527d9acc99`
  - **Week cap ID**: `96de0d17-e408-417b-bd00-cf58102a8bda`
  - **Month cap ID**: `a5573ce4-65cc-49b0-9ceb-5b67db8e6673`

**Older adult group ID**: `d9a7c51e-bcbd-4a2d-92fe-38267e4926525`

- Should _already_ have all the same product IDs associated with it as the `test group`

Additionally, I do have group information for groups that had been created for `people with disabilities` and `youth`, as those were going to be in-person options before the restrictions got put in place. I am continuing to hold on to them because I'm not sure if we can do anything with them right now. Let me know if you'd like me to share those right now as well, hold on to them, discuss further, etc. cc @indexing

**Comment by o-ram** [comment]
Thank you!! Can you refresh my memory on how the test Login.gov credentials work? Is it the same process as described in this [old SacRT doc](https://drive.google.com/drive/search?q=test%20credentials)? Basically, Nevada follows the steps to set up a sandbox account and then enrolls? Or do we provide test data?

**Comment by thekaveman** [comment]
> Thank you!! Can you refresh my memory on how the test Login.gov credentials work? Is it the same process as described in this [old SacRT doc](https://drive.google.com/drive/search?q=test%20credentials)? Basically, Nevada follows the steps to set up a sandbox account and then enrolls? Or do we provide test data?

Yes, Nevada staff will need to create their own sandbox Login.gov account. We have more details in the [Benefits Testing Data doc](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?tab=t.0#heading=h.bvwe1dyv15c5)

The official Login.gov docs are here: https://developers.login.gov/testing/#testing-identity-proofing

Nevada can use our sample [`proofing-senior.yml`](https://drive.google.com/file/d/18Pmc04xIdpzQVyCBez1syZdXjdbsKpCh/view?usp=drive_link) file for an Older Adult.

**Comment by o-ram** [comment]
Thank you @thekaveman! Test instructions have been passed along to Nevada County.

**Comment by thekaveman** [comment]
Today I provided Nevada County staff access to our [`proofing-senior.yml`](https://drive.google.com/file/d/18Pmc04xIdpzQVyCBez1syZdXjdbsKpCh/view?usp=sharing) file for creating an eligible Older Adult Login.gov sandbox account.

**Comment by o-ram** [comment]
A Nevada County staff member successfully created a sandbox account and used it to enroll in Benefits. I can confirm that the test group in the Littlepay production portal now shows 2 cards as being linked to this group.
<img width="831" alt="Image" src="https://github.com/user-attachments/assets/593f2289-a490-4753-86c5-d95601c189f2" />


Testing is planned to take place next week, so I will check in with the agency in early Jan!

**Comment by indexing** [comment]
I spoke with @o-ram yesterday. Testing is underway, and it revealed some issues, so go-live _may_ be the week of 1/13, but more likely the following week, 1/20.

**Comment by o-ram** [comment]
Update! Robin is conducting the final test scenarios over the end of this week and start of next week. There is also some troubleshooting going on with the vendors regarding location info accuracy. 

**Good news: the discounted products worked as expected, and there are no issues on that side of things.**

<img width="1674" alt="Image" src="https://github.com/user-attachments/assets/b02fb3f3-ed75-418f-8059-ae7c20ecb6c7" />




**_Launch?_** Looking at a tentative _public_ launch date of the **first week of Feb**. Things might all be live before then, but would be kept very quiet if so. So, I think we have the ability to push to production this month as long as there is no press/comms/attention from our side.

**Comment by indexing** [comment]
@o-ram I propose we do exactly as you discuss here: a soft launch. Let's configure and launch Nevada County to production as soon as you give us the thumbs up. They can they promote when they are ready.

We'll move when you give us the word.

**Comment by indexing** [comment]
I learned yesterday that Nevada County is now targeting March 10, 2025 for their soft launch. Thus, I've moving this issue to the March sprint. cc// @thekaveman @o-ram

**Comment by o-ram** [comment]
**Pushing Nevada County to prod is a go for March 10, 2025!**! This is a soft launch and _no external communications should take place from Cal-ITP/our partners_.

cc @indexing @thekaveman

**Comment by thekaveman** [comment]
@lalver1 @machikoyasuda @thekaveman configured Nevada County in production:

![Image](https://github.com/user-attachments/assets/47a8f5eb-f9a8-49e9-808e-8b05b4280862)
