### ISSUE TITLE
Update TransitAgency model to ref many EligibilityVerifier

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#320]
## Background

This is the central change outlined in #317, here scoped to allow the model refactor to happen in a non-breaking way that can be built upon in subsequent tasks.

## Tasks

- [x] Convert the [`eligibility_verifier` field](https://github.com/cal-itp/benefits/blob/dev/benefits/core/models.py#L120) from the single  `ForeignKey` to a `ManyToManyField` and rename it to the plural `eligibility_verifiers`
- [x] Update the [initial migration](https://github.com/cal-itp/benefits/blob/dev/benefits/core/migrations/0001_initial.py#L84) since we rebuild the database from scratch each deploy
- [x] Update the [fixtures](https://github.com/cal-itp/benefits/blob/dev/fixtures/04_transitagency.json) to rename the field and wrap the existing value in a list `[]`
- [x] Update usages of the `TransitAgency.eligibility_verifier` attribute in python code to `TransitAgency.eligibility_verifiers[0]` (for now)
- [x] Update the [Eligibility API Client](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/api.py#L117) to accept a `verifier` parameter in addition to `agency`, instead of assuming the `verifier` from the `agency`
- [x] Update [initialization of the Client](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L88) with `agency=agency` and  `verifier=agency.eligibility_verifiers[0]` (for now)
