### ISSUE TITLE
Track EligibilityVerifier in user session

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#321]
## Background

As part of #317 the application will need maintain the user's selected `EligibilityVerifier`.

We can do this using the existing [`session` framework](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py) which keeps everything local to the user in secure cookies.

## Tasks

- [x] Add a [new key `_VERIFIER = "verifier"`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L28) for use elsewhere
- [x] Create a new function `verifier()` that uses the key to get the `EligibilityVerifier` instance corresponding to the saved value from the session; see [`agency()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L35) and [`eligibility()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L87) as examples
- [x] Update the [`update()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L192) function to accept a new kwarg `verifier=None`; if not None and it is a valid `EligibilityVerifier` instance, store the `id` in the request's session using the key
- [x] Update the [`reset()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L134) function to also clear the verifier
- [x] Update the [`context_dict()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L52) function to add the new key/value - this shows up in the debug bar
- [ ] Store the agency's first verifier in session (for now) when an agency is configured
- [ ] Retrieve the verifier from session to give to the API client
