### ISSUE TITLE
Django form to capture user's EligibilityVerifier selection

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#322]
## Background

Building on #320 and #332, once a `TransitAgency` has multiple `EligibilityVerifier` references, the user needs a way to select which one they will use for verification.

Django has the [`ChoiceField`](https://docs.djangoproject.com/en/3.2/ref/forms/fields/#choicefield) which can use the `widget=RadioSelect` to render as a list of radio buttons. The field takes a list of `choices`, each a tuple where the first item is the value and the second is the label:

```
from django import forms

choices = [("value1", "Label One"), ("value2", "Label Two")]
field = forms.ChoiceField(choices=choices, widget=forms.RadioSelect)
```

See e.g. https://stackoverflow.com/a/5925240/453168

## Tasks

* [x] Create a new form class like `EligibilityVerifierSelectionForm` in [`benefits/eligibility/forms.py`](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/forms.py); form should `POST` to `eligibility:index`
* [x] Add a `ChoiceField` using `widget=RadioSelect`
* [x] Create an `__init__()` method accepting an `agency` parameter
* [x] Seed the `ChoiceField.choices` from the `agency.eligibility_verifiers` property, using the above `choices` structure as an example
* [ ] Rework the [`eligibility:index` view](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L16) to handle both `GET` and `POST`
  * for `GET`: If agency has multiple verifiers, initialize form with the selected agency's verifiers and send to the template; otherwise store the one verifier in session and immediately redirect to `eligibility:start`
  * for `POST`: store the selected verifier in session and redirect to `eligibility:start`

**Comment by thekaveman** [comment]
FYI @angela-tran I moved a few of these items (creating the new sample data) to #338, so this one is now strictly to implement the form logic.
