### ISSUE TITLE
Update eligibility verification form to use dynamic data

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#324]
## Background

This builds on #208 and #319 to incorporate specific `EligibilityVerifier` properties into the [eligibility verification form](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/forms.py#L15)

## Tasks

* [x] Create an `__init__()` method on the form class accepting a new kwarg `verifier` of type `EligibilityVerifier`
* [x] If the `verifier.form_sub_pattern` field has a value, add a `pattern` attribute with the value to the `sub` input via [Widget.attrs](https://docs.djangoproject.com/en/3.2/ref/forms/widgets/#django.forms.Widget.attrs)
* [x] If the `verifier.form_name_max_length` field has a value, add a `maxlength` attribute to the `name` input via Widgets.attrs
* [x] Use attributes from the `verifier` as `msgid` keys for labels etc.
* [x] Rework the [`eligibility:confirm` view](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L46) to initialize the `Page` viewmodel and eligibility verification form from the selected verifier

**Comment by thekaveman** [comment]
RE: the final task to use the new form text properties from #319 -- we have to be careful of when to use the **lazy** versions of Django's helper functions for text translations.

E.g. in [`benefits/eligibility/forms.py`](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/forms.py#L7):

```python
from django.utils.translation import gettext_lazy as _
```

Different from e.g. [`benefits/eligibility/views.py`](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L8):

```python
from django.utils.translation import gettext as _
```

Read more about [lazy translation in Django](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#lazy-translation)
