### ISSUE TITLE
Adapt eligibility view logic for multiple verifiers

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#325]
## Background 

This issue builds on the work in #320, #321, #322, #323, and #324 - each of those is a prerequisite before this can be worked on.

With all the model, session, and API changes in place, the last step is to wire them all together with the view logic. 

## Tasks

* [ ] Create a new [verifier fixture](https://github.com/cal-itp/benefits/blob/dev/fixtures/02_eligibilityverifier.json) from the existing one, with a new `pk` and `fields.name`
* [ ] Wire the above fixture to one of the [sample agencies](https://github.com/cal-itp/benefits/blob/dev/fixtures/04_transitagency.json)
* [ ] Rework the [`eligibility:index` view](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L16) to handle both `GET` and `POST`
  * for `GET`: If agency has multiple verifiers, initialize form with the selected agency's verifiers and send to the template; otherwise store the one verifier in session and immediately redirect to `eligibility:instructions`
  * for `POST`: store the selected verifier in session and redirect to `eligibility:instructions`
* [ ] Rework the [`eligibility:confirm` view](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L46) to initialize the `Page` viewmodel and eligibility verification form from the selected verifier
* [ ] Apply the `VerifierSessionRequired` middleware from #323 to `eligibility:instructions` ~`eligibility:confirm`~ (moved to #323)
* [x] ~Rework the [`_verify()`](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L77) helper to initialize the API Client with the selected verifier~ done in #321 instead

**Comment by thekaveman** [comment]
These tasks have been moved to other more relevant issues. Removing this as a dupe.
