### ISSUE TITLE
Refactor language files for multiple verifiers

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#338]
## Background

We need message strings for multiple verifiers

## Tasks

* [x] Create a new [verifier fixture](https://github.com/cal-itp/benefits/blob/dev/fixtures/02_eligibilityverifier.json) from the existing one
  * [x] With a new `pk` and `fields.name`
  * [x] Adjust both to have different `msgid`, e.g. `eligibility.pages.confirm.dmv.*` and `eligibility.pages.confirm.mst.*`
* [x] Adjust the `django.po` files with new `msgid` and new sample content for the Courtesy Cards verifier for each language
* [x] Wire the above fixture to one of the [sample agencies](https://github.com/cal-itp/benefits/blob/dev/fixtures/04_transitagency.json)

## Testing

Once #322 is merged

* [x] Remove your local db and local compiled language files, then run `bin/init.sh`
  * [x] Observe that the migrations run correctly, the fixture data is loaded, and the language files are compiled
* [x] Open the app locally and select the agency configured above with multiple verifiers
  * [x] Observe the `eligibility:index` view with different verifier selections
* [x] Select one of the verifiers
  * [x] Observe the verifier-specific `eligibility:start` view
  * [x] Confirm verification of a test user
* [x] Go back to `eligibility:index` and select the other verifier
  * [x] Observe the verifier-specific `eligibility:start` view
  * [x] Confirm verification of a test user
