### ISSUE TITLE
Add event for verifier selection

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#342]
Soon users will have multiple pathways to verify eligibility, and it would be useful to know how many users are taking which pathway(s) in our analytics.

Once we have multiple verifier pathways, there will be UI to support the selection of pathway. We should have events in response to this new UI.

Linking this Amplitude reference again: https://help.amplitude.com/hc/en-us/articles/115002380567-User-properties-and-event-properties

## Tasks

* [ ] Build on #875 
* [ ] Create a new custom Event `"selected verifier"`, following [an existing Custom event](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/analytics.py#L13) as an example
* [ ] Create a helper to wrap sending of the new event; follow [an existing helper](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/analytics.py#L26) as an example
* [ ] Use the new helper to send the event during `POST` to `eligibility:index` if the form is valid

**Comment by thekaveman** [comment]
With the `started eligibility` and `finished eligibility` events, let's also send the `eligibility` that was checked
