### ISSUE TITLE
Update rendering of Agency index page

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#367]
## Background

In tandem with #366, this ticket moves the bulk of the contextual information from the application index to the agency index.

We need more flexibility on this page than the current viewmodel / page template allows for.

![image](https://user-images.githubusercontent.com/1783439/160712671-c67eee3c-7aef-4bba-bf95-c317699b7de3.png)

## Tasks

* [x] Create/update text entries in English and Spanish for each paragraph, title, etc.
* [x] Can we embed the **bold** font style in the translation?
* [x] Create text entries for a pre-button label / subhead
* [x] Create a new template `core/agency_index.html` to use for this page
* [x] In the view use the new template

**Comment by angela-tran** [comment]
The latest screen for this page from the Figma mockup is:
![image](https://user-images.githubusercontent.com/25497886/163292292-31975ee4-5e3f-4a57-83b6-513c8e542716.png)
