### ISSUE TITLE
Minor style enhancements

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#369]
A number of light enhancements to the overall site look and feel

## Tasks

* [x] Update the main banner background color to `#2b6597` - this comes from the [`.bg-primary` override](https://github.com/cal-itp/benefits/blob/dev/benefits/static/css/styles.css#L72) in our stylesheet
* [x] Update the logo `.svg` files to match the above change, swapping `#046b99` for `#2b6597`
* [x] Primary action buttons (e.g. "Get Started" on the `core:agency_index` page or "Check Status" on the `eligibility:confirm` page should remain `#046b99`
* [x] Primary action buttons (see above) should be displayed in ALL CAPS
* [x] Outline action buttons (e.g. the agency selection buttons on the `core:index` page) should remain  `#046b99`
* [x] Link buttons (e.g. the agency selection buttons on the `core:index` page) should remain  `#046b99`
* [x] Update the footer background color (`.global-footer`) to `#212121`
* [x] Verify font sizes, weights, etc. match the Mocks
