### ISSUE TITLE
Create middleware that expects user to be authenticated

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#371]
## Background

Once the session tracks the sign in status in #370, we can make use of that infrastructure to put guards on certain view functions that require a user to be authenticated with Login.gov. The first step is to create a new middleware class that enforces the requirement.

This is similar to how the [`AgencySessionRequired`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/middleware.py#L20) and [`EligibileSessionRequired`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/middleware.py#L68) middleware are used.

See also #323 / #333 for a very similar task from last Sprint.

We also need the feature flag from #372.

## Tasks

- [x] Create a new middleware class like `AuthSessionRequired` inheriting from `MiddlewareMixin`, see the other `*SessionRequired` as examples
- [ ] In `process_request()`:
  - If the session's verifier is empty, or does not have auth enabled, return `None` to allow the request to continue
  - If the session's verifier has auth enabled, and the session's auth status is `False`, raise an error to stop the request
  - Otherwise return `None` to allow the request to continue
- [ ] Apply this middleware to the following views to enforce that the user must be signed-in:
  - [ ]  [`eligibility:confirm`](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L90)
  - [ ]  [`enrollment:token`](https://github.com/cal-itp/benefits/blob/dev/benefits/enrollment/views.py#L96)
  - [ ]  [`enrollment:index`](https://github.com/cal-itp/benefits/blob/dev/benefits/enrollment/views.py#L109)

**Comment by thekaveman** [comment]
#414 was merged, and since it was built on #409, it closed this issue.

Reopening since we still need this.
