### ISSUE TITLE
Model settings for SSO

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#372]
## Background

We'll need to use a configuration object for a JavaScript library that helps implement the Login.gov flow. 

### Configuration data

Here's what the configuration object eventually needs to look like in JavaScript:

```js
// base address of Benefits application
const baseAddress = "https://localhost:8000";

// configuration object
var config = {
  // authorization server address
  authority: "https://login.gov",
  
  // this is registered application id with auth server
  client_id: "UUID",
  
  // post-login, user is redirected here
  redirect_uri: baseAddress + "/callback.html",
  
  // post-logout, user is redirected here
  post_logout_redirect_uri: baseAddress + "/index.html",
  
  // must be "code" to use the authorization-code flow
  response_type: "code",
  
  // space-delimited list
  // since you do not need any information (claims) about the user, "openid" is the only needed scope.
  // If you need refresh tokens, you must add the "offline_access" scope
  scope: "openid",
};
```

## Tasks

* [x] Build out the list of necessary config items (keys, URLs, endpoints, etc.) - *see above ⬆️*
* [x] Create a model like `AuthProvider` with text fields for the above list, all required
  * [ ] Consider storing URL parameters as the name of the app route, e.g. `eligibility:confirm` so we can use the Django helpers like `reverse()` and `{% url %}` and not duplicate raw paths in data 
* [x] Add a `ForeignKey` for `AuthProvider` to the `EligibilityVerifier` model, make it optional
* [x] Create a wrapper bool attribute on the `EligibilityVerifier` that denotes whether Auth is configured (the **"feature flag"**) by checking if there is a linked provider or not
* [x] Create attributes to track the Sign in + Sign out buttons  `msgid`s
