### ISSUE TITLE
Consume authentication server response data

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#373]
We need a way to take the results of the Login.gov flow (whatever indicates that the user was successful in that flow) and store it via #370.

The scope of this ticket is handling the submission back to our app on the Django side. The sign on button itself will be implemented in #375.

In any case, this PR needs to build upon #375's solution to get the OIDC client library.

## More information from sample

In the sample Login.gov integration app, after the user successfully authenticates with Login.gov, the auth flow sends the user to a `redirect_uri`. This page must call a library function `signinRedirectCallback()` to complete the login.

In the sample, this is implemented with a simple `callback.html` file like:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <script src="libs/oidc-client.js"></script>
    <script>
        new Oidc.UserManager({ response_mode: "query" }).signinRedirectCallback().then(function () {
            window.location = "index.html";
        }).catch(function (e) {
            console.error(e);
        });
    </script>
</body>
</html>
```

## Tasks

* [ ] Create a [new urlpath](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/urls.py) `auth_redirect`
* [ ] Create a [new form](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/forms.py) `AuthRedirect`
* [ ] Create a [new template](https://github.com/cal-itp/benefits/tree/dev/benefits/eligibility/templates/eligibility) `auth-redirect.html`
  * [ ] Extend the `core/page.html` template
  * [ ] Following the above example, submit the form on the page (instead of setting the `window.location`). See [`enrollment:index`](https://github.com/cal-itp/benefits/blob/dev/benefits/enrollment/templates/enrollment/index.html#L40) for a similar example
* [ ] Create a new view function `auth_redirect(request)`:
  * [ ] `GET` should send the form to the template, see e.g. [`eligibility:start`](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L83)
  * [ ] `POST` should update the session to `auth = True` (#370) and redirect to `eligibility:confirm`

**Comment by thekaveman** [comment]
Closing this in favor of a server-only, see revised #375.
