### ISSUE TITLE
Implement OIDC sign in flow

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#375]
## Background

Before the user can verify their information with the DMV API, they must authenticate with the Login.gov SSO system. This task is to implement the [OpenID Connect](https://openid.net/connect/) (OIDC) flow -- built on OAuth 2.0 -- that Login.gov supports.

There are two steps:

1. The user is sent from the Benefits application to the OIDC auth server, where they enter credentials. Upon successful login, the user is redirected back to the Benefits application with an *access token*
2. The access token from the prior step is sent back to the OIDC auth server for validation

Since the Benefits application (server code) must track that the user is signed in (see #370), we need both of these steps to occur on the server in order to trust the results of the access token validation.

Once the access token has been validated, the user is effectively "signed in" from the point of view of the Benefits app.

Build on #380 which places the button on the page.

## Tasks

* [x] When the user clicks the "Continue with Login.gov" button, OIDC redirect to the auth server
* [x] Implement a callback view to receive the OIDC callback redirect (after user logs in), which is a `GET` with querystrings containing the access token
* [x] If the access token is validated, update the user's session to set `auth = True`
