### ISSUE TITLE
Update Enrollment success page

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#376]
## Background

This ticket adds additional contextual information to the final success screen.

![image](https://user-images.githubusercontent.com/1783439/160731515-124338a6-f987-4dd7-a1e2-43236170705a.png)

## Tasks

* [x] Update existing entries for `enrollment.pages.success.p*` to match the new style, in English and Spanish files (these were missed in #328)
* [x] Update the existing language as needed in English and Spanish
* [x] Create text entries to split up the final paragraph at the "help page" link in English and Spanish
* [x] Create text entries for the final sub-heading "Please close your browser..." in English and Spanish
* [x] Update [`enrollment/success.html`](https://github.com/cal-itp/benefits/blob/dev/benefits/enrollment/templates/enrollment/success.html) to render this new content
