### ISSUE TITLE
Update analytics events for Login.gov flow

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#377]
## Background

We'll be introducing some new steps in the flow to support the Login.gov integration. Also the login requirement is being moved further into the overall application flow, so begin in our app flow before hitting the Login.gov flow.

Crucially, we need to understand any "drop off" points, where the user may either get distracted before starting the Login.gov flow, or abandon the application altogether during the Login.gov sign on.

## Tasks

* [x] "started sign in" event for clicking the "Continue to Login.gov" button
  * [x] `event_property` for the `auth_provider=OAUTH_CLIENT_NAME`
* [x] "finished sign in" after successful authorization
  * [x] `event_property` for the `auth_provider=OAUTH_CLIENT_NAME`
* [x] Update the "clicked link" event to also cover URLs containing a hash (e.g. `#payment-options` if the user clicks `/help#payment-options`)
* [x] "started sign out" for when the "Sign out of Login.gov" button is clicked (#368)
    * [x] `event_property` for `auth_provider=OAUTH_CLIENT_NAME`
* [x] "finished sign out" for after the user is redirected back into `post_logout` (see #436 implementation)
    * [x] `event_property` for `origin`
    * [x] `event_property` for `auth_provider=OAUTH_CLIENT_NAME`

**Comment by thekaveman** [comment]
I started some of the basics for this in #452 - feel free to build off that PR if you get to this before I can come back to it.

**Comment by thekaveman** [comment]
@angela-tran thanks for picking this back up!

Based on the implementation we're going towards in #436 - can you mirror the `started/finished sign in` events with `started/finished sign out` with the same attributes? Instead of just the single `signed out` that I listed above (and started with in #452).

**Comment by angela-tran** [comment]
Re: this bullet point,
> * [ ] Update the "viewed page" event to include a custom `event_property` for the URL fragment / hash (e.g. `#payment-options` if the user clicks `/help#payment-options`)

I'm seeing from various sources that the anchor in the request URL is not sent to the server.
 - [Get anchor tag from Django request URL](https://stackoverflow.com/questions/65249426/get-anchor-tag-from-django-request-url)
 - [Is the anchor part of a URL being sent to a web server?](https://stackoverflow.com/questions/3067491/is-the-anchor-part-of-a-url-being-sent-to-a-web-server)

Confirmed in the debugger that we don't have that URL fragment available on the server side. Here I went to the `help#about` URL:
![image](https://user-images.githubusercontent.com/25497886/165173370-7f51bc79-e0e3-4d7f-9b9b-781abe32936d.png)

**Comment by thekaveman** [comment]
> the anchor in the request URL is not sent to the server

Ah, that makes sense.

Another way to get the same data could be to append a querystring to each of the links, with the same value of the hash. That would get sent to the server and could be used...

I think we need to care about this for knowing if/how often folks are going to e.g. the Login.gov help info.

**Comment by angela-tran** [comment]
Reopening because #452 closed only part of this issue

**Comment by angela-tran** [comment]
Updated description to remove crossed out bullet points and, more importantly, to reflect that we'll use a client-side approach to send analytics about the user clicking Help anchor links (well, really any anchor link).
