### ISSUE TITLE
Add sign on button on Eligibility Start page

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#380]
## Background

Build on #374 to work in the template specific to this page. This task is to simply add the button with accurate visual look/feel _when needed_; implementing the functionality is in #375.

### Placement, look, and feel

As a guide to what is covered under this task, see the following visual mock:
 
![image](https://user-images.githubusercontent.com/1783439/160729460-21e79159-20e2-4223-a4ac-06f3234740cd.png)

Note that the exact location and look of this button may change.

## Tasks

* [x] New style for _External action_ button using `#2b6597` as the outline and text color, squared corners; see [CA State Template buttons](https://template.webstandards.ca.gov/sample/buttons.html) for more
* [x] Grab the arrow icon from Figma and save as a local `.svg` to use in the button
* [x] Show the new button if the feature flag in #372 is enabled
* [x] Otherwise a button to forward to the `eligibility:confirm` page as normal
