### ISSUE TITLE
Add tests for Django app

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#413]
Add tests for Django app.

## Chores

* [x] Install Pytest and Pytest Django (#455)
* [x] Set up GitHub Action to get Pytest to run on every PR (#454)
* [x] Set up test to run on every code change? Watcher for devcontainer?

## Tests

Potential good candidates for unit testing in Benefits

* [x] The session #226 (#474)
* [ ] Middleware (https://github.com/cal-itp/benefits/pull/487)
* [ ] Models - interactions between models
* [ ] Settings - are the settings correctly read from environment and set? e.g. is database created in the right place, validate feature flags, etc.
* [ ] Open redirects (#415)
* [ ] Check session [cookie security settings](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#security)
* [ ] OpenID Connect (OIDC) / OAuth 2.0 token verification
* [x] Accessing pages that require auth, following #371
* [x] OAuth login functions (#476)

## Tools

- Does require us to work with a session, so maybe that’s a reason for using Django’s testing tools - https://docs.djangoproject.com/en/3.2/topics/testing/advanced/#the-request-factory

**Comment by machikoyasuda** [comment]
Related to #226

**Comment by afeld** [comment]
Split out some issues; moving to Backlog.

**Comment by afeld** [comment]
Since there are issues for the remaining (meaty) items, closing.
