### ISSUE TITLE
Place Login.gov sign out button

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#428]
## Background

Once the user goes through the Login.gov flow and has successfully signed in to their Login.gov account, they are redirected back to the Benefits application.

We want to give the user a visual indication that "something has changed" with their status; we also want to provide a safe off-ramp for users that may not be able to complete the flow before stepping away from their browser session.

This task is just about placing the button with the right visual look/feel on the correct pages.

## Button placement, look, and feel

As a guide to where to place a sign out button, here are the latest mockups where this appears:

![image](https://user-images.githubusercontent.com/25497886/165826758-b1a10169-2740-4a40-9e24-78b2d7a354f7.png)

![image](https://user-images.githubusercontent.com/25497886/165826768-7b1dc959-72d3-4944-95c8-37884ba877fb.png)

## Tasks

* [x] Display on `eligibility:confirm`
* [x] Display on `enrollment:index`
*  ~Display on `enrollment:success`~ `enrollment:success` uses a different visual that was implemented by #466
* [x] Only display when auth is enabled, and the user is logged in

**Comment by afeld** [comment]
@srhhnry working on updated mockups.

**Comment by machikoyasuda** [comment]
These pages will also need the Log out button:

- [ ] Enrollment unverified
- [ ] Eligibility unverified
