### ISSUE TITLE
Ensure OAuth redirect URLs are secure

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#442]
We construct the OAUth redirect URLs using the Django [`reverse()`](https://docs.djangoproject.com/en/3.2/ref/urlresolvers/#reverse) helper and [`request.build_absolute_uri()`](https://docs.djangoproject.com/en/3.2/ref/request-response/#django.http.HttpRequest.build_absolute_uri).

This is done in e.g. the [`login()` view](https://github.com/cal-itp/benefits/blob/dev/benefits/oauth/views.py):

```python
ROUTE_AUTH = "oauth:authorize"

route = reverse(ROUTE_AUTH)

redirect_uri = request.build_absolute_uri(route)
```

The docs for `build_absolute_uri` say:

> Mixing HTTP and HTTPS on the same site is discouraged, therefore [build_absolute_uri()](https://docs.djangoproject.com/en/3.2/ref/request-response/#django.http.HttpRequest.build_absolute_uri) will always generate an absolute URI with the same scheme the current request has. If you need to redirect users to HTTPS, it’s best to let your Web server redirect all HTTP traffic to HTTPS.

When running in AWS, we have the Load Balancer sitting in front of all requests; this is the layer where HTTP --> HTTPS redirection happens and where the cert that the browser sees is installed.

Then the request gets to the application container, where it first hits `nginx`. This is where requests for static files end; application requests are forwarded through to `gunicorn` over a Unix socket. Strictly speaking, Django does not receive an HTTPS request.

## Potential solution

The [`SECURE_PROXY_SSL_HEADER`](https://docs.djangoproject.com/en/3.2/ref/settings/#secure-proxy-ssl-header) Django setting seems to be aimed at helping this situation, where `nginx` sets a header with an indicated value on the request forwarded into the application via gunicorn, to tell the app if the request was originally secure or not.

In the app's [`nginx.conf`](https://github.com/cal-itp/benefits/blob/dev/nginx.conf#L55) we do set that header on forwarded requests.

## Todo

* [ ] Ensure the current `nginx.conf` setting overwrites any header value coming in with the request and/or clear that header first
* [ ] Add the `SECURE_PROXY_SSL_HEADER` to `settings.py` when `DEBUG = False`

**Comment by thekaveman** [comment]
When running in AWS, we have the Load Balancer sitting in front of all requests; this is the layer at which HTTP --> HTTPS redirection happens and where the HTTPS certificate that the browser sees is installed.

Then the request gets to the application container, where it first hits `nginx`. This is where requests for static files end; application requests are forwarded through to `gunicorn` over a Unix socket. Strictly speaking, Django does not receive an HTTPS request.

The [`SECURE_PROXY_SSL_HEADER`](https://docs.djangoproject.com/en/3.2/ref/settings/#secure-proxy-ssl-header) Django setting seems to be aimed at helping this situation, where `nginx` sets a header with an indicated value on the request forwarded into the application via gunicorn.

In the app's [`nginx.conf`](https://github.com/cal-itp/benefits/blob/dev/nginx.conf#L55) we do set that header on forwarded requests.

## Todo

* [ ] Ensure the current nginx.conf setting overwrites any header value coming in with the request and/or clear that header first
* [ ] Add the `SECURE_PROXY_SSL_HEADER` to `settings.py` when `DEBUG = False`
