### ISSUE TITLE
English copy updates

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#522]
I went through the copy on `https://dev-benefits.calitp.org` and compared with the [Finalized Copy document](https://docs.google.com/document/d/1xSznvvHuhOdtXUuOq1QNMseyfry3PD5oVSvokI9a-E4/edit#) (final updates this morning 4/29/22 8:30am Pacific).

Whatever is on this list needs an update. Anything not on this list matched.

## `core:index`

* [x] Page title: `Choose Provider`
* [x] Button label: `Please choose your transit provider:`

## `core:agency_index`

* [x] Page title to: `Introduction`
* [x] [Body paragraphs](https://docs.google.com/document/d/1xSznvvHuhOdtXUuOq1QNMseyfry3PD5oVSvokI9a-E4/edit#bookmark=id.js88webu44eh)
* [x] Button label: `Connect your bank card to your discount today!`

## `eligibility:start`

* [x] Page title to: `Get Started`
* [x] Main heading: `There are three steps to link your transit discount to your bank card.`
* [x] Item 1
  * [x] Label: `1. Sign in to Login.gov`
  * [x] Body: `Login.gov is a safe way to sign in to government services.`
* [x] Item 2:
  * [x] Body: `You will need to verify your age with a driver’s license or ID card.`

## `eligibility:confirm`

* [x] Page title to: `Confirm Eligibility`
* [x] Main heading: `Let’s see if we can confirm your age with the DMV.`
* [x] [Body paragraph](https://docs.google.com/document/d/1xSznvvHuhOdtXUuOq1QNMseyfry3PD5oVSvokI9a-E4/edit#bookmark=id.94514dyrbb8g)
* ~Form field label: `CA driver license or ID number *`~

## `enrollment:index`

* [x] Page title to: `Connect Card`
* [x] [Body paragraphs](https://docs.google.com/document/d/1xSznvvHuhOdtXUuOq1QNMseyfry3PD5oVSvokI9a-E4/edit#bookmark=id.wf8jwf7c04s4)
* [x] Button text: `CONNECT YOUR CARD`
* [x] Remove "What if I don't have a bank card?" link

## `enrollment:success`

* [x] Page title to: `Success`
* [x] [Body paragraphs](https://docs.google.com/document/d/1xSznvvHuhOdtXUuOq1QNMseyfry3PD5oVSvokI9a-E4/edit#bookmark=id.w3undjeu1dm2)

## `core:help`

* [x] [What is Cal-ITP Benefits?](https://docs.google.com/document/d/1xSznvvHuhOdtXUuOq1QNMseyfry3PD5oVSvokI9a-E4/edit#bookmark=id.d7q26vdwq3ih) #525
* [x] [Payment options](https://docs.google.com/document/d/1xSznvvHuhOdtXUuOq1QNMseyfry3PD5oVSvokI9a-E4/edit#bookmark=id.5wc2xvotqhss) #527
* [x] [What is Login.gov?](https://docs.google.com/document/d/1xSznvvHuhOdtXUuOq1QNMseyfry3PD5oVSvokI9a-E4/edit#bookmark=id.nr9mfymb0b7i) #528 
* [x] [What is Littlepay?](https://docs.google.com/document/d/1xSznvvHuhOdtXUuOq1QNMseyfry3PD5oVSvokI9a-E4/edit#bookmark=id.bxgsdvu4vgyv) #529

**Comment by thekaveman** [comment]
Completed by all the linked PRs, amazing work @machikoyasuda @angela-tran!
