### ISSUE TITLE
Action to add issues to the Project Board

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#570]
We'd like to ensure all issues get added to the [Project Board](https://github.com/orgs/cal-itp/projects/8), but this can be easy to overlook when submitting a new issue, even more so for those unfamiliar with our workflow.

The [`add-to-project`](https://github.com/actions/add-to-project) step can be used here in a new workflow.

## Todo

- [x] Generate a PAT from @cal-itp-bot with scopes `repo`, `write:org`, `read:org` per [`add-to-project`](https://github.com/actions/add-to-project#creating-a-pat-and-adding-it-to-your-repository)
- [x] Add PAT as org-level secret `GH_PROJECTS_TOKEN`
- [x] Create new workflow using `add-to-project`
  - [x] `project-url`: `https://github.com/orgs/cal-itp/projects/8`
  - [x] Run on `issues.types.[opened, transferred]`; see [`add-to-project` Supported Events](https://github.com/actions/add-to-project#supported-events)
  - [x] Will `pull_request.types.opened` work for Dependabot PRs? (e.g. with an `if:` condition in the steps)
