### ISSUE TITLE
College Discount (50%)

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#614]
**Date**: November 2022
**Writers**: 
**Status**:  In Design
**Priority**: [See Roadmap](https://docs.google.com/document/d/1IFoa8Ye0IXwGXXwxFjMrm1s3617Dbv6l-E-aCB0kgnA/edit#)

[Teamwork project](https://calitp.teamwork.com/#/projects/869317/tasks/list)

[Milestone](https://github.com/cal-itp/benefits/milestone/24)

## Background

**Who**: Students and employees at California State University Monterey Bay (CSUMB), students at Hartnell College and Monterey Pacific College (MPC)
**What**: A half-off discount on MST fares during summer and winter break, in addition to their current benefit of free fares during the school term
**When**: During the off-term parts of the year - summer and winter break

**How**: Users will log into their school single sign-on (SSO) to verify their eligibility, and then be directed to the payment card discount enrollment flow. More on architecture, in the [Use Case docs](https://docs.calitp.org/benefits/use-cases/students/).

## Acceptance criteria

- The Benefits application is configured to support verification of eligible college status at multiple colleges
- Customer Service teams at MST and colleges have the resources to support their customer's questions
- A user can navigate to benefits.calitp.org/mst, (optionally) select to verify with their college status and continue on to enroll their contactless payment card with Littlepay
- The Help page is updated with relevant necessary information

## Definition of Done

New releases of Benefits published with release notes.

## User Stories

- [ ] As a User Story, I want to be verifiable, so that this epic can be satisfied

## Tasks

- [ ] Get data sharing agreements signed
- [x] https://github.com/cal-itp/benefits/issues/667
- [x] https://github.com/cal-itp/benefits/issues/779
- [x] https://github.com/cal-itp/benefits/issues/1099
- [ ] Design discount/college selection interface(s)
- [ ] Implement discount/college selection interface(s)
- [x] https://github.com/cal-itp/benefits/issues/1075
- [ ] Set up single sign-on (SSO) with:
   - [ ] CSUMB
   - [ ] Hartnell
   - [ ] MPC
- [ ] Draft communications for schools

## Implementation Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Acceptance criteria is verifiable
- [ ] User workflows defined / designed
- [ ] External / 3rd Party dependencies identified

## Links, resources
- [Demonstration Requirements for Participating Universities and Colleges](https://docs.google.com/document/d/1bpiTqB6QYkjnDkGl5zYN9U184TikVdy7OkpbWb78k38/edit#heading=h.ka9snkgoszvk)
- [Proposal: Student Discounts Using an LMS Plugin](https://docs.google.com/document/d/1ltTyW4jiVEl-Tjs3lolw0PzFIQdUuCZPN6306LffOnU/edit#heading=h.qnh3w1n2hgct)
- [MST Students Demonstration Running Notes](https://docs.google.com/document/d/1kBLQyQeHdz8R-0sv5LMM8rwN1YmAuItrcpbuukvV1Eg/edit#heading=h.3n7j6o55kkyr)

**Comment by afeld** [comment]
Moved tasks from the [resource planning](https://docs.google.com/document/d/1EGLplnM3FFU7zJY3Bsb0CLjlbepxK0r1te1uPoFOlMc/edit#heading=h.1msg372ptlzc) into Tasks above; more details there that should make their way into issues.

**Comment by thekaveman** [comment]
Blocked waiting for the signing of data sharing agreements / contracts.

**Comment by indexing** [comment]
Closing until relevant
