### ISSUE TITLE
Complete hosting migration to Azure

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#615]
We have an initial CI/CD pipeline working for deployments into Azure. This epic tracks the outstanding tasks before we are "officially" in Azure.

## Acceptance Criteria

- [x] The app no longer deploys to AWS
- [x] There are at least 2 separate deployment slots in the Azure environment (in addition to the production app):
  - [x] `dev`
  - [x] `test`
- [x] The app is online and functioning at the corresponding URL
  - [x] `dev-benefits.calitp.org`
  - [x] `test-benefits.calitp.org`
  - [x] `benefits.calitp.org`

## Tasks

- [x] #631
- [x] Upload and configure SSL cert
- [x] Configure `dev` slot in Azure
  - [x] App settings
  - [x] Fixture - Update with changes from #635 
  - [x] [DNS](https://dash.cloudflare.com/4ba2e9699b092e727f64fa2d68d9e762/calitp.org/dns)
    - [x] Azure verify CNAME
    - [x] AppService custom domain
    - [x] AppService custom domain cert binding
    - [x] ~`dev-benefits.calitp.org` CNAME~ Azure FrontDoor configuration change
    - [x] Custom domain configured in Azure FrontDoor Backend Host Header setting
  - [x] Deployment settings
    - [x] [repository Webhook](https://github.com/cal-itp/benefits/settings/hooks/359827986)
    - [x] Update Azure Deployment Center settings `ghcr.io/cal-itp/benefits:dev` 
    - [x] ~`APPLICATIONINSIGHTS_CONNECTION_STRING`~ see #861 
  - [x] VNet integration
  - [x] Update DMV IP allowlist
  - [x] Run the complete flow on dev-benefits.calitp.org
- [x] Update [documentation](https://docs.calitp.org/benefits/deployment/)
  - [x] some in #603
  - [x] #670
- [x] #603
- [x] Configure `test` slot in Azure
  - [x] App settings
  - [x] Fixture - Update with changes from #635 
  - [x] [DNS](https://dash.cloudflare.com/4ba2e9699b092e727f64fa2d68d9e762/calitp.org/dns)
    - [x] Remove NS records for AWS
    - [x] Azure verify CNAME
    - [x] `test-benefits.calitp.org` CNAME
    - [x] AppService custom domain
    - [x] AppService custom domain cert binding
    - [x] Azure FrontDoor configuration for new app service slot
    - [x] Custom domain configured in Azure FrontDoor Backend Host Header setting
  - [x] Deployment settings
    - [x] [repository Webhook](https://github.com/cal-itp/benefits/settings/hooks/363487600)
    - [x] Update Azure Deployment Center settings `ghcr.io/cal-itp/benefits:test`
    - [x] ~`APPLICATIONINSIGHTS_CONNECTION_STRING`~ see #861 
  - [x] VNet integration
- [x] Configure production app in Azure
  - [x] App settings
  - [x] Fixtures
  - [x] Path mapping for fixture
  - [x] [DNS](https://dash.cloudflare.com/4ba2e9699b092e727f64fa2d68d9e762/calitp.org/dns)
    - [x] Remove NS records for AWS
    - [x] Azure verify `awverify.benefits.calitp.org CNAME awverify.as-cdt-pub-vip-calitp-p-001.azurewebsites.net`
    - [x] `benefits.calitp.org CNAME fd-cdt-shrd-p003.azurefd.net`
    - [x] AppService custom domain
    - [x] AppService custom domain cert binding
    - [x] Azure FrontDoor configuration for new app service slot @cal-itp/cdt-devsecops 
    - [x] Custom domain configured in Azure FrontDoor Backend Host Header setting @cal-itp/cdt-devsecops 
  - [x] Deployment settings
    - [x] Repository webhook
    - [x] ~`APPLICATIONINSIGHTS_CONNECTION_STRING`~ see #861 
  - [x] VNet integration

## Additional context

Prior work towards this:

* #586 
* #587 
* #588 
* #589 
* #590 
* #592 
* #593 
* #594

**Comment by thekaveman** [comment]
Currently blocked waiting for CDT to create the Production subscription in Azure.

**Comment by thekaveman** [comment]
* Currently unable to connect to CDT Auth Server in UAT
* Currently blocked because we can't #631 so cannot diagnose issue properly

**Comment by thekaveman** [comment]
As noted in #861, we removed the `APPLICATIONINSIGHTS_CONNECTION_STRING` from `dev` and `prod` (it was not set in `test`) to workaround a bug and get the app live.

Will use that issue to track adding these settings back in.

**Comment by thekaveman** [comment]
We are live at all 3 environments in Azure!
