### ISSUE TITLE
Login.gov IAL2 for age verification (seniors)

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#635]
**Date**: June 2022
**Writers**: @thekaveman @vykster @machikoyasuda @angela-tran @srhhnry @Indiajar @o-ram @jarrettkrumrei 
**Status**: In-Progress
**Priority**: [No. 1 per the Roadmap](https://docs.google.com/document/d/1IFoa8Ye0IXwGXXwxFjMrm1s3617Dbv6l-E-aCB0kgnA/edit#)

## Background
Login.gov is a digital identity management tool developed by the federal government and in use for a growing number of applications, recently this tool has been made available to state governments. Login.gov offers two account types, with the second an IAL2-like account users can "proof" their identity. Many older adults already use login.gov to access their SSI benefits. Integrating with a login.gov account allows us a reliable online source of someone's status as qualified for a senior program (65 years or older). Federal funding for transit includes requirements of operators that they offer senior discounts to riders. 

## Decision drivers
Age verification needs to be behind an identity proofed flow, age needs to be verified by a third-party. 

## Decision outcome

Given we are already integrating with the login.gov to create accounts, migrating to the the login.gov IAL2* identity proofed account type and using [user attributes](https://developers.login.gov/attributes/) to verify age allows us a rapid and controlled timeline without waiting for other the DMV to implement the id-linking tools and provides user experience than is possibly less confusing. Current limitations of this approach include the complex account registration process and strict requirement that users have a social security number, as from our research we know not all riders eligible for the senior discount programs have social security numbers. However given the use of [Login.gov for Supplemental Security Income (SSI)](https://secure.ssa.gov/RIL/SiView.action) we expect out of all groups of transit riders, older adults to have the most familiarity with login.gov.

We will need to accommodate flows for three classes of errors: 

* Eligibility not verified
* Login.gov failure
* Payment card not verified

## Acceptance criteria

- [x] Acceptance criteria

## Definition of Done

Benefits is live in production, older adults (age 65+) can login with an IAL2* proofed Login.gov account, and continue on to enroll their contactless payment card with Littlepay.

## User Stories

- [x] As a new Login.gov user, I want to understand what is required for an IAL2* proofed account, so that I know what to expect in the sign-up process
- [x] As a new Login.gov user, I want to proof my identity with Login.gov using IAL2*, so that I can verify my age in Benefits
- [x] As an existing Login.gov user, I want to login to my IAL2* proofed account, so that I can verify my age in Benefits
- [x] As an older adult without a SSN I want to quickly understand I am not able to use the current tool so I don't get frustrated in attempting to create an account. 

## Tasks

Carrying over from #363 / still need to complete

* [x] **Engineering**: https://github.com/cal-itp/benefits/issues/621
* [x] **Engineering**: #615
* [x] **Product**: #636 (Needs to be assigned)

New tasks

Design

- [x] **Design**: #642
- [x] **Design**: #643
- [x] **Design/Copy**: Finalize English copy. Get copy approved by whoever needs to approve it. Hand off English copy to @o-ram for Spanish translations.
- [x] **Copy**: Get Spanish Translations for new copy @o-ram 

Engineering

- [x] #730 
- [x] #644
- [x] Implement Littlepay failure flow page
- [x] #689
- [x] #707
- [x] #713
- [x] **Engineering**: After Designs are finalized and approved, write any more Engineering tickets necessary.
- [x] #656
- [x] #654
- [x] #653
- [x] #655 @machikoyasuda 
- [x] #674
- [x] #678
- [x] #640
- [x] #641

Copy/Engineering

- [x] #676
- [x] #705
- [x] #706
- [x] #702

Product/Testing

- [x] **Product**: Define user acceptance testing process
- [x] **Engineering**: #672

Comms

- [ ] **Communications**: #650
- [ ] **Communications**:  #645

## Implementation Ready Checklist

- [x] Acceptance criteria defined
- [x] Team understands acceptance criteria
- [x] User workflows defined / designed
- [x] Acceptance criteria is verifiable
- [x] External / 3rd Party dependencies identified

## Links, resources

- [Cal-ITP Benefits Product Roadmap](https://docs.google.com/document/d/1IFoa8Ye0IXwGXXwxFjMrm1s3617Dbv6l-E-aCB0kgnA/edit#)
- [Login.gov: How to verify your identity](https://login.gov/help/verify-your-identity/how-to-verify-your-identity/)
- [Login.gov Developer Resource User attributes](https://developers.login.gov/attributes/)

**Comment by machikoyasuda** [comment]
Higher res version of edited photo https://drive.google.com/file/d/1IzPr2lk-9ShXPRZNVMVHOv9ky3B26VJR/view

**Comment by thekaveman** [comment]
Closing this Epic, we have deployed Login.gov IAL2 age verification for seniors 65+
