### ISSUE TITLE
Update success flow: logged in, eligibility verified, payment card connected

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#642]
Epic: #635 

## Tasks

- [x] Drop out all DMV screens in Desktop and Mobile flow
- [x] Redesign Get Started pages in Desktop and Mobile
- [x] Scan each page for DMV copy and remove or rewrite
- [x] Update Help screen to accommodate IAL2 
- [x] Update Help screens to remove references to DMV
- [x] Integrate IAL2 information in Get Started page
- [x] Update Finalized Copy document to reflect changes

**Comment by srhhnry** [comment]
All desktop screens here: https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(IAL2-Login.gov)?node-id=3753%3A6485

All mobile screens here: https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(IAL2-Login.gov)?node-id=3830%3A9833

**Comment by srhhnry** [comment]
New finalized copy doc available here: https://docs.google.com/document/d/1Ndai_9Ut6DLU86w6BpkmU23xzG1QF0a0-BeQ3_FWNoQ/edit?usp=sharing
