### ISSUE TITLE
Set up continuous deployment for infrastructure as code

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#666]
In order to have greater consistency, visibility, and security, it is desirable to have infrastructure as code (IaC) changes automatically deployed.

## Acceptance Criteria

- [ ] `plan`ned changes are reflected in / linked from open pull requests
- [ ] Once merged (to `dev`? `prod`?), changes should be automatically `apply`d

## Tasks

- [x] Authorize Azure DevOps GitHub App
- [x] [Set up service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#create-a-service-connection)

## Additional context

[sp]: https://docs.microsoft.com/en-us/learn/modules/authenticate-azure-deployment-pipeline-service-principals/

Open questions:

- What branch do we want to use to deploy changes to the Production resource group?
- Do we also want to deploy changes to the Development resource group?
- What system should be used for doing so?

System | Pros | Cons
--- | --- | ---
GitHub Actions | Already used for continuous integration and deployment of the app, so engineering team is comfortable with it | Easy to mistakenly output something sensitive\*
[Azure Pipelines][ap] | @cal-itp/cdt-devsecops use it for other projects; output is private; will have deeper integration with Azure services | Pipelines would live in two places
[Terraform Cloud][tc] | Purpose-built for this; output is private | Yet Another Thing for people to learn, pay for, manage, get approved, etc.

\*Unless it's moved to a private repository

[ap]: https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/what-is-azure-pipelines
[tc]: https://cloud.hashicorp.com/products/terraform

Relevant docs:

- https://docs.microsoft.com/en-us/learn/modules/authenticate-azure-deployment-pipeline-service-principals/
- https://docs.microsoft.com/en-us/azure/app-service/deploy-best-practices
- https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-iaas
- https://julie.io/writing/terraform-on-azure-pipelines-best-practices/

**Comment by afeld** [comment]
@cal-itp/cdt-devsecops to provide a template for Azure Pipelines, and we may do a working session this week to get it set up.

**Comment by afeld** [comment]
See email thread `Terraform pipeline` for the sample from @srivanimulpuru. @sureshtekyentra set up the `Production` [Service Connection](https://calenterprise.visualstudio.com/CDT.OET.CAL-ITP/_settings/adminservices) for us, so this is now unblocked.

**Comment by afeld** [comment]
[First `apply` from an Azure Pipeline](https://calenterprise.visualstudio.com/CDT.OET.CAL-ITP/_build/results?buildId=34539&view=logs&j=bc150913-bfac-577d-ab97-4eb22da69064&t=5c01d50c-3bf9-589e-956a-833a2240feb3) worked!
