### ISSUE TITLE
Complete penetration tests

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#672]
Follow-up to https://github.com/cal-itp/benefits/issues/521.

## Acceptance Criteria

- [ ] We are made aware of open security vulnerabilities

## Tasks

- [x] Update [testing plan](https://docs.google.com/document/d/1MDtGR01OkdEi9kOQVNM0dsHfYgvOoEiDqVZ2JHYbNng/edit#)
- [x] Reach back out to Bugcrowd about updated schedule: would like to start testing Wed 6/22
- [x] BugCrowd
  - [x] Test started
- [x] Jemurai
  - [x] Test started
  - [x] Findings received
  - [x] Create issues for any findings

**Comment by afeld** [comment]
Testing by Jemurai has started; waiting to hear about timeline from BugCrowd.

**Comment by afeld** [comment]
Jemurai scans completed; [artifacts](https://drive.google.com/drive/folders/1Zb2risjywexN71l4D2jqe_cTiUUuHKVc). Still waiting on BugCrowd to start.

**Comment by afeld** [comment]
BugCrowd bounty has begun.

**Comment by afeld** [comment]
New requirement from the CDT ISO that we have a penetration test performed by "A California Military Department". @jarrettkrumrei is getting more details.

**Comment by thekaveman** [comment]
CMD completed; [artifacts](https://drive.google.com/drive/folders/1S7kRq-F7WBw9e2Fcbf-Z7SlXSZtR4S3r?usp=sharing).

Presented all findings to CDT ISO, collating remediations/notes for final approval next week Thursday August 11.

**Comment by afeld** [comment]
Will track that approval as part of https://github.com/cal-itp/benefits/issues/621.
