### ISSUE TITLE
infrastructure pipeline improvements

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#803]
**Date**: 7/19/22
**Writers**: @afeld
**Status**: Placeholder

## Acceptance criteria

- [ ] Acceptance criteria

## Definition of Done

A clear and concise description of what "Done" means for this Epic.

## User Stories

- [ ] As a User Story, I want to be verifiable, so that this epic can be satisfied

## Tasks

Collecting ideas; we might decide different ones are different priority or not worthwhile.

- [ ] https://github.com/cal-itp/benefits/issues/1234
- [x] #829
- [ ] Terraform locking improvements
   - [x] Ensure those actions (`plan` and `apply`) are running one at a time - https://github.com/cal-itp/benefits/pull/876
   - [ ] Better handle pipeline cancellations/timeouts
      - [Cleanup tasks](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
      - [Longer timeouts](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts), maybe
- [ ] Leverage Azure Pipeline features
   - [ ] Environments
   - [ ] Releases

## Implementation Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Acceptance criteria is verifiable
- [ ] User workflows defined / designed
- [ ] External / 3rd Party dependencies identified

## Links, resources

- Other links here

**Comment by afeld** [comment]
Other issues have been split out, so closing as low priority.
