### ISSUE TITLE
Make Release: 2022.08.2

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#885]
### Release manager

@thekaveman

### Release version

2022.08.2

### What type of release is this?

Regular

### Release checklist

- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into the staging target, merge #886 
- [x] (If applicable): open another PR from dev to test #887
- [x] QA the app in test @angela-tran @machikoyasuda ✅ 
- [x] Open a PR to for the test branch into prod, merge #884
- [x] QA the app in prod
- [x] Tag the release on the prod branch, push the tag to GitHub
- [x] Create a release in GitHub for the tag, generating release notes: https://github.com/cal-itp/benefits/releases/tag/2022.08.2
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by thekaveman** [comment]
Released!
