### ISSUE TITLE
velocity improvement recommendations

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#902]
@vykster asked me to look into ways that the velocity of the Benefits team could be improved.

## TODOs

- [x] [Brainstorm around areas for improvement](https://docs.google.com/document/d/1QRYIFWiAWjKCF44Fbt8Cu-DVpeAtWtoQM_d97F2l3RU/edit)
- [x] [Conduct interviews with members of the team](https://cal-itp.slack.com/archives/C037Y3UE71P/p1661802438787089)
- [x] Review retro notes
   - [x] [TeamRetro](https://compiler.teamretro.com/teams/4qcYBIIYhRKrS26XCrb5bB/retrospectives)
   - [x] [Sprint Planning notes](https://docs.google.com/document/d/1EGLplnM3FFU7zJY3Bsb0CLjlbepxK0r1te1uPoFOlMc/edit)
- [x] Put together slides with findings
- [ ] Share findings with Compiler
- [ ] Set up brainstorming session to prioritize and come up with solutions

## Acceptance Criteria

- [ ] Recommendations provided

## What is the definition of done?

There are specific recommendations / next steps recommended to @vykster and the team, which can then be prioritized (or not)

**Comment by afeld** [comment]
[Discussion about deliverable](https://docs.google.com/document/d/1BdfEl3bDHzoOXKRZOQZWGMmnscxE58OsB3FDiyQ1vfQ/edit#bookmark=id.oyui1tl83cbf)

**Comment by vykster** [comment]
thanks Aidan for sharing the notes, I noticed on a few items you've started making GitHub issues. For now, could you hold off on doing that? I feel like it's creating a bit of noise at the moment before we've finished the process of investigation.

**Comment by afeld** [comment]
Holding on this until November.
