### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#905]
**Date**: 9/9/22
**Writers**: @afeld
**Status**: Draft

## Background

Now that the app is live with real users, we want to:

- Ensure availability/reliability of the system
- Receive timely, relevant alerts if something goes wrong
- Ensure the team has the tools, information, and processes to troubleshoot and fix problems that may arise and prevent them from reoccurring

While this will require improvement indefinitely, this Epic is about doing a chunk of those things to get to a better place.

## Acceptance criteria

- [ ] Acceptance criteria

## Definition of Done

A clear and concise description of what "Done" means for this Epic.

## User Stories

- [ ] As a User Story, I want to be verifiable, so that this epic can be satisfied

## Tasks

- [ ] https://github.com/cal-itp/benefits/issues/803
- [ ] Perform incident response tabletop exercises
- [ ] Confirm that [logs](https://docs.calitp.org/benefits/deployment/infrastructure/#logs) are functioning properly
   - [ ] Look into [alternative options](https://docs.google.com/document/d/1e79AHO5WkDbDwyGY2uDfiKKNvToPLxp7AIaIl_Ul4GQ/edit#heading=h.j4euvlrq8rqx)
- [ ] https://github.com/cal-itp/benefits/issues/832
- [ ] https://github.com/cal-itp/benefits/issues/733
- [ ] Create an incident response checklist
   - [Incident Management Plan](https://docs.google.com/document/d/1qtev8qItPiTB4Tp9FQ87XsLtWZ4HlNXqoe9vF2VuGcY/edit#)
- [ ] https://github.com/cal-itp/benefits/issues/830
- [ ] https://github.com/cal-itp/benefits/issues/728
- [ ] Budget alerts
- [ ] Expirations
   - [ ] Domains
   - [ ] Certificates
- [ ] Smoke test(s)
- [ ] Response times
- [ ] Traffic

## Implementation Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Acceptance criteria is verifiable
- [ ] User workflows defined / designed
- [ ] External / 3rd Party dependencies identified

## Links, resources

- Other links here

**Comment by afeld** [comment]
[Notes from September Sprint Planning](https://docs.google.com/document/d/1EGLplnM3FFU7zJY3Bsb0CLjlbepxK0r1te1uPoFOlMc/edit#bookmark=id.5robanotw9ro)

**Comment by afeld** [comment]
Upon reflection, most of the tasks above are around _high availability_: enabling it, measuring it, or making it easier to recover. Using a broad definition of "availability" here: ["the ability of the user community to obtain a service or good,"](https://en.wikipedia.org/wiki/High_availability) beyond just "you can get to the homepage." Still ok with "reliability" if we want to cast a wider net.

**Comment by afeld** [comment]
[Kickoff notes](https://docs.google.com/document/d/1flO3UxDswH-bqIceDCWHqpsvKLX3mwyDH0_jPJF3xRc/edit#), where most of the topics were outside of Benefits. Meeting with @vykster and @mrose914 to confirm scope/staffing.

**Comment by afeld** [comment]
Given this effort is going to be broader than Benefits, moved to [a Milestone under Services Team](https://github.com/cal-itp/services-team/milestone/1).

**Comment by afeld** [comment]
Keeping [the Milestone under Benefits](https://github.com/cal-itp/benefits/milestone/23) for Benefits-specific work.
