### ISSUE TITLE
Make a Release: 2022.09.1

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#907]
### Release manager

@angela-tran 

### Release version

2022.09.1

### What type of release is this?

Regular

### Release checklist

- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into the staging target, merge - #915
- [x] (If applicable): open another PR from dev to test - #917 
- [x] QA the app in test @machikoyasuda @angela-tran 
- [x] Open a PR to for the test branch into prod, merge - #918
- [x] QA the app in prod
- [x] Tag the release on the prod branch, push the tag to GitHub
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by machikoyasuda** [comment]
Release notes:

## Overview

This release contains a number of small improvements for analytics, dependency security updates and more.

- **Analytics**: Renames `provider_name` to `transity_agency`. Returns `eligibility_group_id` as `payment_group` for successful enrollment events 
- **Public Key**: Updates `TransitAgency` public key. **This PR requires database schema updates.**
- For developers: Adds environment variables and settings to be compatible with the latest [Eligibility Server](https://github.com/cal-itp/eligibility-server/)
