### ISSUE TITLE
Publish Login.gov Impact Story

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#992]
Login.gov publishes [impact stories](https://login.gov/partners/impact-stories/), which are case studies of their partners. Could be useful for getting more awareness around the app.

## Acceptance Criteria

- [ ] There is an Impact Story published around the Benefits app / Identity Gateway

## Additional context

We should be able to adapt the [press release](https://www.calitp.org/assets/Cal-ITP.Benefits.PressRelease.220921.pdf) pretty easily.

## Tasks

- [ ] Pitch idea to Login.gov
- [ ] Get confirmation from Login.gov they would like us to do so
- [ ] Write first draft
- [ ] Get draft reviewed
- [ ] Publish

**Comment by afeld** [comment]
@jarrettkrumrei Is there a specific point of contact at Login.gov you'd recommend for this?

**Comment by indexing** [comment]
@vykster Is this a marketing effort we want to pursue?

**Comment by vykster** [comment]
Yes, it would be a good idea to do this next sprint if possible.

**Comment by indexing** [comment]
@vykster Who at Compiler (or Cal-ITP?) usually generates marketing content like this? I will see if we can address this late in the July sprint as a stretch item.

**Comment by vykster** [comment]
currently it's more of short straw draw. Let's ask Meryl for help.

**Comment by machikoyasuda** [comment]
https://www.gsa.gov/blog/2024/08/26/gsas-logingov-expands-services-into-states
